import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { RaceSimulation,createCar,FIXED_DT,nearestTrack,trackPoint,trackTangent,TRACK_WIDTH } from '@agp/sim-core';
import { DeterministicDriver,decisionToControl,observe } from '@agp/driver-sdk';
import type { Control,RaceConfig,RaceState,ReplayFile,Weather } from '@agp/shared';
import { ENTRANTS,TEAMS,type Entrant } from './championship';
export type CameraMode='broadcast'|'trackside'|'chase'|'cockpit'|'aerial'|'neural';

export class ConnectomeScene{
 private scene=new THREE.Scene();private camera=new THREE.PerspectiveCamera(43,1,.1,1400);private renderer:THREE.WebGLRenderer;private sim!:RaceSimulation;private drivers=new Map<string,DeterministicDriver>();private controls=new Map<string,Control>();private cars=new Map<string,THREE.Group>();private entrants=new Map<string,Entrant>();private template:THREE.Group|null=null;private raf=0;private last=0;private acc=0;private paused=true;private mode:CameraMode='broadcast';private kind:'live'|'replay'|'human'='live';private emitAt=0;private resize:()=>void;private focus=ENTRANTS[0].id;private speed=1;private replay:ReplayFile|null=null;private replayT=0;private replayEnd=0;private keys=new Set<string>();private touch={left:false,right:false,gas:false,brake:false,boost:false};private rain!:THREE.Points;private weather:Weather='CLEAR';private audio:AudioContext|null=null;private osc:OscillatorNode|null=null;private gain:GainNode|null=null;private low=matchMedia('(max-width:760px),(prefers-reduced-motion:reduce)').matches;
 constructor(private el:HTMLElement,private onState:(s:RaceState)=>void,private onReplay?:(t:number,d:number)=>void){this.renderer=new THREE.WebGLRenderer({antialias:!this.low,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,this.low?1:1.35));this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.12;this.renderer.shadowMap.enabled=!this.low;el.appendChild(this.renderer.domElement);this.resize=()=>{this.camera.aspect=Math.max(.2,el.clientWidth/el.clientHeight);this.camera.updateProjectionMatrix();this.renderer.setSize(el.clientWidth,el.clientHeight,false)};addEventListener('resize',this.resize);addEventListener('keydown',this.down);addEventListener('keyup',this.up);this.resize();this.world();this.startRace({session:'GRAND_PRIX',laps:3,entrants:22,weather:'CLEAR',seed:4127});void this.loadModel();}
 private down=(e:KeyboardEvent)=>this.keys.add(e.code);private up=(e:KeyboardEvent)=>this.keys.delete(e.code);
 startRace(cfg:RaceConfig){this.clear();this.kind=cfg.session==='HUMAN_TEST'?'human':'live';this.replay=null;this.replayT=0;this.weather=cfg.weather;this.applyWeather();const selected=ENTRANTS.slice(0,cfg.session==='NEUTRAL_TEST'?22:Math.max(1,Math.min(22,cfg.entrants))).map(x=>({...x}));if(this.kind==='human')selected[0]={...selected[0],id:'human',name:'HUMAN TEST',short:'HUMAN',number:99,teamId:'neutral',teamName:'AGP DEVELOPMENT',colour:'#F4E8CE',secondary:'#073BBE',accent:'#D7A647',phenotypeId:'HUMAN-INPUT'};const states=selected.map((e,i)=>{const t=TEAMS.find(x=>x.id===e.teamId),c=createCar(e.id,e.name,e.number,e.colour,i,cfg.session==='NEUTRAL_TEST'?undefined:t?.tuning);c.teamId=e.teamId;c.teamName=e.teamName;return c});this.sim=new RaceSimulation(states,cfg.laps,cfg.seed,cfg.weather);for(const e of selected){this.entrants.set(e.id,e);if(e.id!=='human'){this.drivers.set(e.id,new DeterministicDriver(e.id,e.name));this.controls.set(e.id,{steering:0,throttle:.72,brake:0,energyDeploy:0})}const g=this.makeCar(e);this.cars.set(e.id,g);this.scene.add(g)}this.focus=selected[0].id;this.paused=false;this.sync();this.onState(this.sim.state)}
 async loadReplay(r:ReplayFile){this.clear();this.kind='replay';this.replay=r;this.replayT=0;this.replayEnd=r.frames.at(-1)?.t??0;this.weather='CLEAR';this.applyWeather();const first=r.frames[0];if(!first)throw new Error('Replay has no frames');const es=first.cars.map((c,i)=>ENTRANTS.find(e=>e.id===c.id)??ENTRANTS[i%ENTRANTS.length]);const states=es.map((e,i)=>{const t=TEAMS.find(x=>x.id===e.teamId),c=createCar(e.id,e.name,e.number,e.colour,i,t?.tuning);c.teamId=e.teamId;c.teamName=e.teamName;return c});this.sim=new RaceSimulation(states,r.laps,r.seed);for(const e of es){this.entrants.set(e.id,e);const g=this.makeCar(e);this.cars.set(e.id,g);this.scene.add(g)}this.focus=es[0].id;this.paused=false;this.frameReplay(0)}
 setCamera(v:CameraMode){this.mode=v}setPaused(v:boolean){this.paused=v}setFocus(id:string){if(this.cars.has(id))this.focus=id}setPlaybackSpeed(v:number){this.speed=Math.max(.25,Math.min(4,v))}seekReplay(v:number){if(this.replay){this.replayT=Math.max(0,Math.min(this.replayEnd,v));this.frameReplay(this.replayT)}}setHumanControl(k:keyof typeof this.touch,v:boolean){this.touch[k]=v}restart(){if(this.replay)void this.loadReplay(this.replay);else this.startRace({session:this.kind==='human'?'HUMAN_TEST':'GRAND_PRIX',laps:this.sim.laps,entrants:this.sim.state.cars.length,weather:this.weather,seed:this.sim.state.seed})}
 async setSound(on:boolean){if(on){this.audio??=new AudioContext();await this.audio.resume();if(!this.osc){this.osc=this.audio.createOscillator();this.gain=this.audio.createGain();this.osc.type='sawtooth';this.gain.gain.value=.018;this.osc.connect(this.gain).connect(this.audio.destination);this.osc.start()}this.gain?.gain.setTargetAtTime(.018,this.audio.currentTime,.04)}else if(this.gain)this.gain.gain.setTargetAtTime(0,this.audio!.currentTime,.04)}
 start(){this.last=performance.now();const loop=(now:number)=>{const d=Math.min((now-this.last)/1000,.05);this.last=now;if(!this.paused){if(this.replay){this.replayT=Math.min(this.replayEnd,this.replayT+d*this.speed);this.frameReplay(this.replayT);if(this.replayT>=this.replayEnd)this.paused=true}else{this.acc+=d;while(this.acc>=FIXED_DT){this.tick();this.sim.step(this.controls,FIXED_DT);this.acc-=FIXED_DT}this.sync()}}this.animate();this.cameraTick(now/1000);this.renderer.render(this.scene,this.camera);if(now>this.emitAt){this.emitAt=now+100;this.onState(this.sim.state);if(this.replay)this.onReplay?.(this.replayT,this.replayEnd)}this.raf=requestAnimationFrame(loop)};this.raf=requestAnimationFrame(loop)}
 private tick(){if(this.kind==='human')this.controls.set('human',this.human());if(this.sim.state.tick%10)return;for(const c of this.sim.state.cars){const d=this.drivers.get(c.id);if(d&&c.status==='RUNNING')void d.decide(observe(this.sim.state,c)).then(x=>this.controls.set(c.id,decisionToControl(x)))}}
 private human():Control{const l=this.keys.has('ArrowLeft')||this.keys.has('KeyA')||this.touch.left,r=this.keys.has('ArrowRight')||this.keys.has('KeyD')||this.touch.right,g=this.keys.has('ArrowUp')||this.keys.has('KeyW')||this.touch.gas,b=this.keys.has('ArrowDown')||this.keys.has('KeyS')||this.touch.brake;return{steering:(l?-1:0)+(r?1:0),throttle:g?1:0,brake:b?1:0,energyDeploy:this.keys.has('Space')||this.touch.boost?1:0}}
 private frameReplay(t:number){if(!this.replay)return;let i=0;while(i+1<this.replay.frames.length&&this.replay.frames[i+1].t<=t)i++;const a=this.replay.frames[i],b=this.replay.frames[Math.min(i+1,this.replay.frames.length-1)],m=a===b?0:(t-a.t)/(b.t-a.t);for(const c of this.sim.state.cars){const x=a.cars.find(q=>q.id===c.id),y=b.cars.find(q=>q.id===c.id)??x;if(!x||!y)continue;c.x=THREE.MathUtils.lerp(x.x,y.x,m);c.z=THREE.MathUtils.lerp(x.z,y.z,m);c.yaw=lerpAngle(x.yaw,y.yaw,m);c.speed=THREE.MathUtils.lerp(x.speed,y.speed,m);c.lap=x.lap;c.position=x.position;c.status=x.status;c.progress=nearestTrack(c.x,c.z).t;if(x.neural)c.neural={phenotypeId:ENTRANTS.find(e=>e.id===c.id)?.phenotypeId??c.id,source:'AGP_SIMULATION_INTERFACE',activeNeurons:x.neural.activeNeurons,spikeRate:x.neural.spikeRate,visualActivity:x.neural.visualActivity,descendingActivity:x.neural.descendingActivity,steeringOutput:x.neural.steeringOutput,throttleOutput:x.neural.throttleOutput,brakeOutput:x.neural.brakeOutput,reinforcementSignal:0,interfaceLatencyMs:0,connectomeSimRate:100}}this.sim.state.time=t;this.sim.state.flag=t>=this.replayEnd?'CHEQUERED':'GREEN';this.sync()}
 private sync(){for(const c of this.sim.state.cars){const g=this.cars.get(c.id);if(!g)continue;g.position.set(c.x,.7,c.z);g.rotation.y=c.yaw;((g.userData.wheels??[]) as THREE.Object3D[]).forEach((w,i)=>{w.rotation.x-=c.speed*FIXED_DT/.38;if(i<2)w.rotation.y=c.controls.steering*.3})}}
 private cameraTick(t:number){const list=[...this.sim.state.cars].sort((a,b)=>a.position-b.position),c=this.sim.state.cars.find(x=>x.id===this.focus)??list[0];if(!c)return;const p=new THREE.Vector3(c.x,1.1,c.z),f=new THREE.Vector3(Math.sin(c.yaw),0,Math.cos(c.yaw));if(this.mode==='chase'){this.camera.position.lerp(p.clone().addScaledVector(f,-12).add(new THREE.Vector3(0,4.5,0)),.08);this.camera.lookAt(p.clone().addScaledVector(f,10))}else if(this.mode==='cockpit'){this.camera.position.lerp(p.clone().add(new THREE.Vector3(0,.7,0)),.35);this.camera.lookAt(p.clone().addScaledVector(f,30))}else if(this.mode==='aerial'){this.camera.position.lerp(new THREE.Vector3(c.x+10,62,c.z+12),.03);this.camera.lookAt(p)}else if(this.mode==='neural'){this.camera.position.lerp(p.clone().add(new THREE.Vector3(Math.sin(t*.35)*6,5,Math.cos(t*.35)*6)),.06);this.camera.lookAt(p)}else{const q=trackPoint((c.progress+.02)%1),tan=trackTangent((c.progress+.02)%1),side=Math.sin(c.progress*29)>0?1:-1,dist=this.mode==='trackside'?11:22,height=this.mode==='trackside'?3.7:8;this.camera.position.lerp(new THREE.Vector3(q.x+tan.z*dist*side,height,q.z-tan.x*dist*side),.04);this.camera.lookAt(p)}}
 private world(){this.scene.background=new THREE.Color('#83B6DA');this.scene.fog=new THREE.FogExp2('#9EC2D8',.0017);this.scene.add(new THREE.HemisphereLight('#EAF7FF','#15251F',2.15),new THREE.AmbientLight('#FFE4B5',.4));const sun=new THREE.DirectionalLight('#FFDDA0',5);sun.position.set(-110,150,-78);sun.castShadow=!this.low;this.scene.add(sun);const water=new THREE.Mesh(new THREE.CircleGeometry(620,this.low?48:96),new THREE.MeshPhysicalMaterial({color:'#0757A0',roughness:.12,metalness:.15,clearcoat:.8}));water.rotation.x=-Math.PI/2;water.position.y=-3.4;this.scene.add(water);const island=new THREE.Mesh(new THREE.CylinderGeometry(184,230,13,64),new THREE.MeshStandardMaterial({color:'#B9A77E',roughness:.94}));island.position.y=-6;this.scene.add(island);this.track();this.scenery();this.makeRain()}
 private track(){const n=this.low?220:380,v:number[]=[],idx:number[]=[];for(let i=0;i<=n;i++){const t=(i%n)/n,p=trackPoint(t),d=trackTangent(t);for(const s of [-1,1])v.push(p.x+d.z*TRACK_WIDTH*.5*s,.05,p.z-d.x*TRACK_WIDTH*.5*s)}for(let i=0;i<n;i++){const a=i*2,b=a+1,c=a+2,d=a+3;idx.push(a,c,b,b,c,d)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(v,3));g.setIndex(idx);g.computeVertexNormals();this.scene.add(new THREE.Mesh(g,new THREE.MeshStandardMaterial({color:'#343A3F',roughness:.9})));for(let i=0;i<n;i+=10){const t=i/n,p=trackPoint(t),d=trackTangent(t);for(const s of [-1,1]){const k=new THREE.Mesh(new THREE.BoxGeometry(.9,.1,2.6),new THREE.MeshStandardMaterial({color:Math.floor(i/10)%2?'#F4E8CE':'#073BBE'}));k.position.set(p.x+d.z*(TRACK_WIDTH*.5+.35)*s,.1,p.z-d.x*(TRACK_WIDTH*.5+.35)*s);k.rotation.y=d.yaw;this.scene.add(k);const rail=new THREE.Mesh(new THREE.BoxGeometry(.25,.7,4.2),new THREE.MeshStandardMaterial({color:'#D8D5C9',metalness:.3}));rail.position.set(p.x+d.z*(TRACK_WIDTH*.5+1.45)*s,.5,p.z-d.x*(TRACK_WIDTH*.5+1.45)*s);rail.rotation.y=d.yaw;this.scene.add(rail)}}}
 private scenery(){const rock=new THREE.MeshStandardMaterial({color:'#9B8A67',roughness:1}),green=new THREE.MeshStandardMaterial({color:'#174A24'});for(let i=0;i<(this.low?12:24);i++){const a=i/24*Math.PI*2,r=145+(i%4)*7,h=18+(i%5)*5,c=new THREE.Mesh(new THREE.CylinderGeometry(9,17,h,7),rock);c.position.set(Math.cos(a)*r,h/2-2,Math.sin(a)*r);this.scene.add(c);const cap=new THREE.Mesh(new THREE.CylinderGeometry(8,11,1.5,7),green);cap.position.set(c.position.x,h-1,c.position.z);this.scene.add(cap)}const deck=new THREE.Mesh(new THREE.BoxGeometry(76,2.3,7.5),new THREE.MeshStandardMaterial({color:'#D6C5A4'}));deck.position.set(68,18,87);deck.rotation.y=-.18;this.scene.add(deck);for(let i=-3;i<=3;i++){const p=new THREE.Mesh(new THREE.BoxGeometry(4,34,4),new THREE.MeshStandardMaterial({color:'#B8A583'}));p.position.set(68+i*10,1,87-i*1.8);this.scene.add(p)}for(let i=0;i<7;i++){const b=new THREE.Mesh(new THREE.BoxGeometry(12,4.6,7),new THREE.MeshStandardMaterial({color:i%2?'#F4E8CE':'#073BBE'}));b.position.set(-54+i*10,2.3,-88);this.scene.add(b)}}
 private makeRain(){const n=this.low?500:1200,a=new Float32Array(n*3);for(let i=0;i<n;i++){a[i*3]=(Math.random()-.5)*360;a[i*3+1]=Math.random()*100;a[i*3+2]=(Math.random()-.5)*300}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(a,3));this.rain=new THREE.Points(g,new THREE.PointsMaterial({color:'#D7ECFF',size:.12,transparent:true,opacity:.6}));this.rain.visible=false;this.scene.add(this.rain)}
 private applyWeather(){const wet=['RAIN','LIGHT_RAIN','HEAVY_RAIN'].includes(this.weather);if(this.rain)this.rain.visible=wet;this.scene.fog=new THREE.FogExp2(wet?'#7899A9':'#9EC2D8',wet ? .0031 : .0017)}private animate(){if(this.rain?.visible){const a=this.rain.geometry.attributes.position as THREE.BufferAttribute;for(let i=0;i<a.count;i++){let y=a.getY(i)-1.4;if(y<0)y=100;a.setY(i,y)}a.needsUpdate=true}const c=this.sim?.state.cars.find(x=>x.id===this.focus);if(this.osc&&c)this.osc.frequency.setTargetAtTime(70+c.speed*3.7,this.audio!.currentTime,.05)}
 private makeCar(e:Entrant){if(this.template){const g=this.template.clone(true),w:THREE.Object3D[]=[];let i=0;g.traverse(o=>{if(o instanceof THREE.Mesh){o.castShadow=!this.low;const m=o.material as THREE.MeshStandardMaterial;o.material=m.clone();const n=(o.name||m.name||'').toLowerCase(),mm=o.material as THREE.MeshStandardMaterial;if(n.includes('tyre')||n.includes('tire')||n.includes('carbon'))mm.color.set('#15191B');else mm.color.set(i++%4?e.colour:e.secondary);if(n.includes('wheel'))w.push(o)}});g.userData.wheels=w;g.scale.setScalar(.92);return g}const g=new THREE.Group(),p=new THREE.MeshPhysicalMaterial({color:e.colour,metalness:.3,roughness:.3,clearcoat:.8}),d=new THREE.MeshStandardMaterial({color:'#111519'}),a=new THREE.MeshStandardMaterial({color:e.accent}),r=new THREE.MeshStandardMaterial({color:'#101214'});const body=new THREE.Mesh(new THREE.BoxGeometry(1.4,.6,4.2),p);body.position.y=.6;g.add(body);const floor=new THREE.Mesh(new THREE.BoxGeometry(2,.2,5.4),d);floor.position.y=.2;g.add(floor);const nose=new THREE.Mesh(new THREE.ConeGeometry(.58,2.4,6),p);nose.rotation.x=Math.PI/2;nose.position.set(0,.5,2.7);g.add(nose);for(const z of [1.8,-1.65])for(const x of [-1.1,1.1]){const w=new THREE.Mesh(new THREE.CylinderGeometry(.47,.47,.35,16),r);w.rotation.z=Math.PI/2;w.position.set(x,.48,z);(g.userData.wheels??=[]).push(w);g.add(w)}const wing=new THREE.Mesh(new THREE.BoxGeometry(2.4,.12,.65),a);wing.position.set(0,.3,3);g.add(wing);return g}
 private async loadModel(){try{this.template=(await new GLTFLoader().loadAsync(new URL('models/agp01.glb',document.baseURI).toString())).scene}catch{this.template=null}}
 private clear(){for(const g of this.cars.values())this.scene.remove(g);this.cars.clear();this.drivers.clear();this.controls.clear();this.entrants.clear()}dispose(){cancelAnimationFrame(this.raf);removeEventListener('resize',this.resize);removeEventListener('keydown',this.down);removeEventListener('keyup',this.up);this.renderer.dispose();this.renderer.domElement.remove();try{this.osc?.stop()}catch{void 0}}
}
function lerpAngle(a:number,b:number,t:number){let d=b-a;while(d>Math.PI)d-=Math.PI*2;while(d<-Math.PI)d+=Math.PI*2;return a+d*t}
