import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { buildPremiumFormulaCar } from './PremiumCar';
import { decoratePremiumCircuit } from './PremiumCircuit';
import { PremiumRaceAudio } from './PremiumAudio';
import { PremiumWeather } from './PremiumWeather';
import { RaceSimulation,createCar,FIXED_DT,trackPoint,trackTangent,TRACK_WIDTH,DEFAULT_2027_TRACK_ID } from '@agp/sim-core';
import { DeterministicDriver,decisionToControl,observe } from '@agp/driver-sdk';
import type { Control,RaceConfig,RaceState,ReplayFile,Weather } from '@agp/shared';

export type CameraMode='broadcast'|'chase'|'cockpit'|'tcam'|'trackside'|'aerial'|'neural';
export type SceneMode='live'|'replay'|'human';
export interface Entrant {id:string;name:string;number:number;colour:string;secondary:string;accent:string;temperament:number;provider:string;model:string;liveryTheory:string;connection:'NOT CONFIGURED'|'LOCAL'|'CONNECTED';}
export const ENTRANTS:Entrant[]=[
  {id:'gpt',name:'GPT',number:10,colour:'#101312',secondary:'#F2F1E8',accent:'#10A37F',temperament:.8,provider:'OPENAI',model:'GPT',liveryTheory:'INK AND IVORY, CUT WITH OPENAI GREEN',connection:'NOT CONFIGURED'},
  {id:'claude',name:'CLAUDE',number:32,colour:'#D97757',secondary:'#F1E8D7',accent:'#1E1D1B',temperament:.35,provider:'ANTHROPIC',model:'CLAUDE',liveryTheory:'TERRACOTTA, WARM PAPER AND QUIET INK',connection:'NOT CONFIGURED'},
  {id:'gemini',name:'GEMINI',number:88,colour:'#4285F4',secondary:'#A142F4',accent:'#F4E8CE',temperament:.55,provider:'GOOGLE',model:'GEMINI',liveryTheory:'GOOGLE BLUE FLOWING INTO GEMINI VIOLET',connection:'NOT CONFIGURED'},
  {id:'grok',name:'GROK',number:24,colour:'#050708',secondary:'#F4E8CE',accent:'#8A9298',temperament:.9,provider:'xAI',model:'GROK',liveryTheory:'BLACK MONOLITH, IVORY TYPE AND STEEL DETAIL',connection:'NOT CONFIGURED'},
  {id:'qwen',name:'QWEN',number:72,colour:'#615CED',secondary:'#38D4FF',accent:'#F4E8CE',temperament:.15,provider:'ALIBABA CLOUD',model:'QWEN',liveryTheory:'QWEN VIOLET WITH DIGITAL CYAN SIGNALS',connection:'NOT CONFIGURED'},
  {id:'deepseek',name:'DEEPSEEK',number:1,colour:'#4D6BFE',secondary:'#EAF0FF',accent:'#15286B',temperament:-.1,provider:'DEEPSEEK',model:'DEEPSEEK',liveryTheory:'ELECTRIC BLUE, ICE WHITE AND DEEP NAVY',connection:'NOT CONFIGURED'},
  {id:'mistral',name:'MISTRAL',number:7,colour:'#F97316',secondary:'#FFCF59',accent:'#071018',temperament:.65,provider:'MISTRAL AI',model:'MISTRAL',liveryTheory:'HOT ORANGE AND AMBER OVER CARBON BLACK',connection:'NOT CONFIGURED'},
  {id:'llama',name:'LLAMA',number:70,colour:'#0668E1',secondary:'#F4E8CE',accent:'#00C2FF',temperament:-.35,provider:'META',model:'LLAMA',liveryTheory:'META BLUE WITH CLEAN IVORY AND CYAN',connection:'NOT CONFIGURED'}
];

export class GrandPrixScene{
  private scene=new THREE.Scene();private camera=new THREE.PerspectiveCamera(42,1,.1,1200);private renderer:THREE.WebGLRenderer;private sim!:RaceSimulation;private drivers=new Map<string,DeterministicDriver>();private controls=new Map<string,Control>();private cars=new Map<string,THREE.Group>();private entrants=new Map<string,Entrant>();private carTemplate:THREE.Group|null=null;private raf=0;private last=0;private acc=0;private paused=true;private mode:CameraMode='broadcast';private sceneMode:SceneMode='live';private emitAt=0;private resize:()=>void;private focusId='gpt';private playbackSpeed=1;private replay:ReplayFile|null=null;private replayTime=0;private replayDuration=0;private keys=new Set<string>();private touch={left:false,right:false,gas:false,brake:false,boost:false};private clouds:THREE.Group[]=[];private water!:THREE.Mesh;private weather:Weather='CLEAR';private raceAudio=new PremiumRaceAudio();private premiumWeather!:PremiumWeather;private lowPower=matchMedia('(max-width: 760px), (prefers-reduced-motion: reduce)').matches;private currentTrackId:string=DEFAULT_2027_TRACK_ID;private trackGroup=new THREE.Group();
  constructor(private el:HTMLElement,private onState:(s:RaceState)=>void,private onReplayProgress?:(time:number,duration:number)=>void){
    this.renderer=new THREE.WebGLRenderer({antialias:!this.lowPower,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,this.lowPower?1:1.3));this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.16;this.renderer.shadowMap.enabled=!this.lowPower;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;el.appendChild(this.renderer.domElement);
    this.resize=()=>{this.camera.aspect=Math.max(.2,el.clientWidth/el.clientHeight);this.camera.updateProjectionMatrix();this.renderer.setSize(el.clientWidth,el.clientHeight,false)};addEventListener('resize',this.resize);addEventListener('keydown',this.keyDown);addEventListener('keyup',this.keyUp);this.resize();this.premiumWeather=new PremiumWeather(this.scene,this.lowPower);this.buildWorld();this.startRace({session:'QUICK_RACE',laps:3,entrants:8,weather:'CLEAR',seed:4127});
  }
  private keyDown=(e:KeyboardEvent)=>{this.keys.add(e.code);};private keyUp=(e:KeyboardEvent)=>{this.keys.delete(e.code);};
  startRace(config:RaceConfig){this.clearCars();this.sceneMode=config.session==='HUMAN_TEST'?'human':'live';this.replay=null;this.replayTime=0;this.weather=config.weather;this.applyWeather();const selected=ENTRANTS.slice(0,Math.max(1,Math.min(config.entrants,ENTRANTS.length)));if(this.sceneMode==='human')selected[0]={...selected[0],id:'human',name:'HUMAN TEST',number:99,colour:'#F4E8CE',secondary:'#073BBE',accent:'#D7A647',provider:'AGP',model:'HUMAN INPUT',liveryTheory:'IVORY AND COBALT AGP DEVELOPMENT LIVERY',connection:'LOCAL'};this.setTrack(config.trackId??DEFAULT_2027_TRACK_ID);const states=selected.map((e,i)=>createCar(e.id,e.name,e.number,e.colour,i,undefined,this.currentTrackId));this.sim=new RaceSimulation(states,config.laps,config.seed,config.weather,this.currentTrackId,config.championshipRound);for(const e of selected){this.entrants.set(e.id,e);if(e.id!=='human'){this.drivers.set(e.id,new DeterministicDriver(e.id,e.name,e.temperament));this.controls.set(e.id,{steering:0,throttle:.82,brake:0,energyDeploy:0});}const mesh=this.makeCar(e);this.cars.set(e.id,mesh);this.scene.add(mesh);}this.focusId=selected[0].id;this.paused=false;this.updateMeshes();this.onState(this.sim.state);}
  async loadReplay(replay:ReplayFile){this.clearCars();this.sceneMode='replay';this.replay=replay;this.replayTime=0;this.replayDuration=replay.frames.at(-1)?.t??0;this.paused=false;this.weather='CLEAR';this.applyWeather();const first=replay.frames[0];if(!first)throw new Error('Replay has no frames');const entrants=first.cars.map((c,i)=>ENTRANTS.find(e=>e.id===c.id)??{...ENTRANTS[i%ENTRANTS.length],id:c.id,name:c.id.toUpperCase()});this.setTrack(replay.trackId??DEFAULT_2027_TRACK_ID);const states=entrants.map((e,i)=>createCar(e.id,e.name,e.number,e.colour,i,undefined,this.currentTrackId));this.sim=new RaceSimulation(states,replay.laps,replay.seed,'CLEAR',this.currentTrackId,replay.championshipRound);for(const e of entrants){this.entrants.set(e.id,e);const mesh=this.makeCar(e);this.cars.set(e.id,mesh);this.scene.add(mesh);}this.focusId=entrants[0].id;this.applyReplayFrame(0);}
  restart(){if(this.replay){void this.loadReplay(this.replay);}else this.startRace({session:this.sceneMode==='human'?'HUMAN_TEST':'QUICK_RACE',laps:this.sim.laps,entrants:this.sim.state.cars.length,weather:this.weather,seed:this.sim.state.seed,trackId:this.currentTrackId,championshipRound:this.sim.state.championshipRound});}
  private tp(t:number){return trackPoint(t,this.currentTrackId)}private tt(t:number){return trackTangent(t,this.currentTrackId)}
  setTrack(trackId:string){const next=trackId||DEFAULT_2027_TRACK_ID;if(next===this.currentTrackId&&this.trackGroup.children.length)return;this.currentTrackId=next;for(const child of [...this.trackGroup.children]){this.trackGroup.remove(child);child.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry?.dispose();const mats=Array.isArray(o.material)?o.material:[o.material];for(const m of mats)m?.dispose();}});}this.makeRoad();this.makeLandscape();this.makeVenue();decoratePremiumCircuit(this.trackGroup,this.currentTrackId,this.lowPower);}
  setCamera(m:CameraMode){this.mode=m;}setPaused(v:boolean){this.paused=v;}setFocus(id:string){if(this.cars.has(id))this.focusId=id;}setPlaybackSpeed(v:number){this.playbackSpeed=Math.max(.25,Math.min(4,v));}setHumanControl(key:keyof typeof this.touch,active:boolean){this.touch[key]=active;}async setSound(enabled:boolean){await this.raceAudio.setEnabled(enabled);}seekReplay(seconds:number){if(!this.replay)return;this.replayTime=Math.max(0,Math.min(this.replayDuration,seconds));this.applyReplayFrame(this.replayTime);}
  start(){this.last=performance.now();const frame=(now:number)=>{const delta=Math.min((now-this.last)/1000,.05);this.last=now;if(!this.paused){if(this.sceneMode==='replay'&&this.replay){this.replayTime=Math.min(this.replayDuration,this.replayTime+delta*this.playbackSpeed);this.applyReplayFrame(this.replayTime);if(this.replayTime>=this.replayDuration)this.paused=true;}else{this.acc+=delta;while(this.acc>=FIXED_DT){this.tickDrivers();this.sim.step(this.controls,FIXED_DT);this.acc-=FIXED_DT;}this.updateMeshes();}}this.animateWorld(now/1000);this.updateCamera(now/1000);this.renderer.render(this.scene,this.camera);if(now>this.emitAt){this.emitAt=now+100;this.onState(this.sim.state);if(this.replay)this.onReplayProgress?.(this.replayTime,this.replayDuration);}this.raf=requestAnimationFrame(frame)};this.raf=requestAnimationFrame(frame);}
  private humanControl():Control{const left=this.keys.has('ArrowLeft')||this.keys.has('KeyA')||this.touch.left,right=this.keys.has('ArrowRight')||this.keys.has('KeyD')||this.touch.right,gas=this.keys.has('ArrowUp')||this.keys.has('KeyW')||this.touch.gas,brake=this.keys.has('ArrowDown')||this.keys.has('KeyS')||this.touch.brake;return{steering:(left?-1:0)+(right?1:0),throttle:gas?1:0,brake:brake?1:0,energyDeploy:this.keys.has('Space')||this.touch.boost?1:0};}
  private tickDrivers(){if(this.sceneMode==='human')this.controls.set('human',this.humanControl());if(this.sim.state.tick%30!==0)return;for(const car of this.sim.state.cars){const d=this.drivers.get(car.id);if(!d)continue;void d.decide(observe(this.sim.state,car)).then(x=>this.controls.set(car.id,decisionToControl(x)));}}
  private applyReplayFrame(time:number){if(!this.replay)return;let lo=0,hi=this.replay.frames.length-1;while(lo<hi){const mid=Math.floor((lo+hi+1)/2);if(this.replay.frames[mid].t<=time)lo=mid;else hi=mid-1;}const a=this.replay.frames[lo],b=this.replay.frames[Math.min(lo+1,this.replay.frames.length-1)],mix=a===b?0:(time-a.t)/(b.t-a.t);for(const car of this.sim.state.cars){const x=a.cars.find(c=>c.id===car.id),y=b.cars.find(c=>c.id===car.id)??x;if(!x||!y)continue;car.x=THREE.MathUtils.lerp(x.x,y.x,mix);car.z=THREE.MathUtils.lerp(x.z,y.z,mix);car.yaw=lerpAngle(x.yaw,y.yaw,mix);car.speed=THREE.MathUtils.lerp(x.speed,y.speed,mix);car.lap=x.lap;car.position=x.position;car.status=x.status;car.progress=trackProgress(car.x,car.z,this.currentTrackId);}this.sim.state.time=time;this.sim.state.tick=Math.round(time/FIXED_DT);this.sim.state.flag=time>=this.replayDuration?'CHEQUERED':'GREEN';this.updateMeshes();this.onState(this.sim.state);}
  private updateMeshes(){for(const s of this.sim.state.cars){const g=this.cars.get(s.id);if(!g)continue;g.position.set(s.x,.72,s.z);g.rotation.y=s.yaw;const wheels=g.userData.wheels as THREE.Mesh[];wheels.forEach((w,i)=>{w.rotation.x-=s.speed*FIXED_DT/.38;if(i<2)w.rotation.y=s.controls.steering*.35;});const rain=g.userData.rainLight as THREE.Mesh|undefined;if(rain)(rain.material as THREE.MeshStandardMaterial).emissiveIntensity=1.5+Math.sin(this.sim.state.time*12)*1.2;const spray=(g.userData.spray??[]) as THREE.Mesh[],sprayPower=this.sim.state.wetness*Math.min(1,s.speed/45);spray.forEach((m,i)=>{m.visible=sprayPower>.035;m.scale.set(1+sprayPower*.9,1+sprayPower*2.2,1+sprayPower*.8);m.rotation.z=(i?-.08:.08)+Math.sin(this.sim.state.time*9+i)*.025;(m.material as THREE.MeshBasicMaterial).opacity=.05+sprayPower*.22;});}}
  private updateCamera(t:number){const targetCar=this.sim.state.cars.find(c=>c.id===this.focusId)??[...this.sim.state.cars].sort((a,b)=>a.position-b.position)[0];if(!targetCar)return;const target=new THREE.Vector3(targetCar.x,1.1,targetCar.z),forward=new THREE.Vector3(Math.sin(targetCar.yaw),0,Math.cos(targetCar.yaw));if(this.mode==='chase'){this.camera.position.lerp(target.clone().addScaledVector(forward,-12.5).add(new THREE.Vector3(0,4.6,0)),.075);this.camera.lookAt(target.clone().addScaledVector(forward,10));}else if(this.mode==='cockpit'){this.camera.position.lerp(target.clone().addScaledVector(forward,.32).add(new THREE.Vector3(0,.62,0)),.38);this.camera.lookAt(target.clone().addScaledVector(forward,34));}else if(this.mode==='tcam'){this.camera.position.lerp(target.clone().addScaledVector(forward,-1.05).add(new THREE.Vector3(0,1.28,0)),.26);this.camera.lookAt(target.clone().addScaledVector(forward,40).add(new THREE.Vector3(0,.15,0)));}else if(this.mode==='neural'){const orbit=new THREE.Vector3(Math.sin(t*.7)*2.8,1.85+Math.sin(t*.9)*.25,Math.cos(t*.7)*2.8);this.camera.position.lerp(target.clone().add(orbit).addScaledVector(forward,-4.2),.08);this.camera.lookAt(target.clone().addScaledVector(forward,5));}else if(this.mode==='aerial'){this.camera.position.lerp(new THREE.Vector3(targetCar.x+12,62,targetCar.z+14),.028);this.camera.lookAt(target);}else if(this.mode==='trackside'){const p=this.tp((targetCar.progress+.018)%1),tan=this.tt((targetCar.progress+.018)%1),side=Math.sin(targetCar.progress*34)>0?1:-1;this.camera.position.lerp(new THREE.Vector3(p.x+tan.z*10*side,3.6,p.z-tan.x*10*side),.05);this.camera.lookAt(target.clone().addScaledVector(forward,3));}else{const marks=[.02,.18,.37,.56,.74,.9],mark=marks[Math.floor((this.sim.state.time/6)%marks.length)],p=this.tp(mark),tan=this.tt(mark),side=Math.sin(mark*29)>0?1:-1,c=new THREE.Vector3(p.x+tan.z*(18+mark*8)*side,8+((mark*100)%8),p.z-tan.x*(18+mark*8)*side);this.camera.position.lerp(c,.024);this.camera.lookAt(target.clone().add(new THREE.Vector3(0,.4,Math.sin(t*.35)*1.2)));}}
  private buildWorld(){this.scene.background=new THREE.Color('#3d86c9');this.scene.fog=new THREE.FogExp2('#8fb8d5',.0017);this.scene.add(new THREE.HemisphereLight('#d8eeff','#17251e',2.45));this.scene.add(new THREE.AmbientLight('#ffe7bd',.45));const sun=new THREE.DirectionalLight('#ffe1a6',5.4);sun.position.set(-105,155,-82);sun.castShadow=!this.lowPower;sun.shadow.mapSize.set(this.lowPower?512:1536,this.lowPower?512:1536);sun.shadow.camera.left=-225;sun.shadow.camera.right=225;sun.shadow.camera.top=190;sun.shadow.camera.bottom=-190;sun.shadow.bias=-.0002;this.scene.add(sun);this.water=new THREE.Mesh(new THREE.CircleGeometry(560,this.lowPower?48:96),new THREE.MeshPhysicalMaterial({color:'#075ba9',roughness:.12,metalness:.18,clearcoat:.8,clearcoatRoughness:.16}));this.water.rotation.x=-Math.PI/2;this.water.position.y=-3.35;this.water.receiveShadow=!this.lowPower;this.scene.add(this.water);const island=new THREE.Mesh(new THREE.CylinderGeometry(184,224,13,this.lowPower?48:72),new THREE.MeshStandardMaterial({color:'#bfae87',roughness:.92}));island.position.y=-5.9;island.receiveShadow=!this.lowPower;this.scene.add(island);this.scene.add(this.trackGroup);this.makeRoad();this.makeLandscape();this.makeVenue();this.makeClouds();}
  private applyWeather(){const heavy=this.weather==='HEAVY_RAIN'||this.weather==='RAIN',light=this.weather==='LIGHT_RAIN'||this.weather==='DRYING',cloud=this.weather==='OVERCAST'||this.weather==='CLOUDY';this.scene.fog=new THREE.FogExp2(heavy?'#5f7487':light?'#758ba0':cloud?'#8296a9':'#6e9cdf',heavy ? .0035:light ? .00225:cloud ? .00185:.00145);this.renderer.toneMappingExposure=heavy ? .79:light ? .91:cloud ? .98:1.16;this.premiumWeather?.setWeather(this.weather);}
  private animateWorld(t:number){this.clouds.forEach((c,i)=>{c.position.x+=.002*(i%3+1);c.rotation.y=Math.sin(t*.015+i)*.02;});this.water.rotation.z=Math.sin(t*.07)*.002;this.premiumWeather.update(t,this.camera);const car=this.sim.state.cars.find(c=>c.id===this.focusId),slip=car?.tyres.reduce((n,x)=>n+Math.abs(x.slipAngle)+Math.abs(x.slipRatio),0)??0;this.raceAudio.update(car?.speed??0,car?.controls.throttle??0,this.sim.state.wetness,this.paused,car?.neural?.spikeRate??0,slip*.12);}
  private makeRoad(){
    const strip=(width:number,y:number,material:THREE.Material)=>{const count=900,pos:number[]=[],idx:number[]=[],uv:number[]=[];for(let i=0;i<=count;i++){const t=(i%count)/count,p=this.tp(t),tan=this.tt(t),nx=tan.z,nz=-tan.x;pos.push(p.x+nx*width/2,y,p.z+nz*width/2,p.x-nx*width/2,y,p.z-nz*width/2);uv.push(0,i/18,1,i/18);if(i<count){const a=i*2;idx.push(a,a+1,a+2,a+1,a+3,a+2);}}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));geo.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));geo.setIndex(idx);geo.computeVertexNormals();const mesh=new THREE.Mesh(geo,material);mesh.receiveShadow=true;this.trackGroup.add(mesh);return mesh;};
    strip(TRACK_WIDTH+3,-.01,new THREE.MeshStandardMaterial({color:'#64605a',roughness:.94}));
    const asphalt=this.makeAsphaltTexture();strip(TRACK_WIDTH,.07,new THREE.MeshStandardMaterial({map:asphalt,color:'#30363a',roughness:.87,metalness:.02}));
    const kerbGeo=new THREE.BoxGeometry(.62,.12,2.15),kerbBlue=new THREE.MeshStandardMaterial({color:'#1353d2',roughness:.64}),kerbIvory=new THREE.MeshStandardMaterial({color:'#f2e8d1',roughness:.58}),kerbs=[new THREE.InstancedMesh(kerbGeo,kerbBlue,260),new THREE.InstancedMesh(kerbGeo,kerbIvory,260)],kerbDummy=new THREE.Object3D(),kerbIndex=[0,0];
    for(let i=0;i<260;i++){const t=i/260,p=this.tp(t),tan=this.tt(t);for(const side of [-1,1]){kerbDummy.position.set(p.x+tan.z*(TRACK_WIDTH*.5+.18)*side,.15,p.z-tan.x*(TRACK_WIDTH*.5+.18)*side);kerbDummy.rotation.set(0,tan.yaw,0);kerbDummy.updateMatrix();const k=i%2;kerbs[k].setMatrixAt(kerbIndex[k]++,kerbDummy.matrix);}}kerbs.forEach(k=>{k.castShadow=!this.lowPower;k.receiveShadow=true;this.trackGroup.add(k);});
    const barrierMat=new THREE.MeshStandardMaterial({color:'#d7d9d8',metalness:.72,roughness:.3}),barrierGeo=new THREE.BoxGeometry(2.55,.56,.13),barriers=new THREE.InstancedMesh(barrierGeo,barrierMat,360),dummy=new THREE.Object3D();let bi=0;
    for(let i=0;i<180;i++){const t=i/180,p=this.tp(t),tan=this.tt(t);for(const side of [-1,1]){dummy.position.set(p.x+tan.z*7.35*side,.67,p.z-tan.x*7.35*side);dummy.rotation.y=tan.yaw;dummy.updateMatrix();barriers.setMatrixAt(bi++,dummy.matrix);}}barriers.castShadow=true;barriers.receiveShadow=true;this.trackGroup.add(barriers);
    const lineMat=new THREE.MeshBasicMaterial({color:'#f4e8ce'});for(const side of [-1,1]){const points=Array.from({length:420},(_,i)=>{const p=this.tp(i/420),tan=this.tt(i/420);return new THREE.Vector3(p.x+tan.z*(TRACK_WIDTH*.5-.45)*side,.145,p.z-tan.x*(TRACK_WIDTH*.5-.45)*side)}),line=new THREE.Mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(points,true),420,.045,4,true),lineMat);this.trackGroup.add(line);}
    const start=this.tp(0),st=this.tt(0);for(let i=0;i<12;i++){const mark=new THREE.Mesh(new THREE.BoxGeometry(.62,.025,1),new THREE.MeshBasicMaterial({color:i%2?'#071018':'#f4e8ce'}));mark.position.set(start.x+st.z*(i-6)*1.02,.16,start.z-st.x*(i-6)*1.02);mark.rotation.y=st.yaw;this.trackGroup.add(mark);}for(let row=0;row<8;row++)for(const side of [-1,1]){const t=(.982-row*.0075+1)%1,p=this.tp(t),tan=this.tt(t),grid=new THREE.Mesh(new THREE.PlaneGeometry(1.7,4.1),new THREE.MeshBasicMaterial({color:'#f4e8ce',transparent:true,opacity:.5,side:THREE.DoubleSide}));grid.rotation.x=-Math.PI/2;grid.rotation.z=-tan.yaw;grid.position.set(p.x+tan.z*2.05*side,.155,p.z-tan.x*2.05*side);this.trackGroup.add(grid);}this.makeGantries();
  }
  private makeAsphaltTexture(){const c=document.createElement('canvas');c.width=c.height=256;const x=c.getContext('2d')!;x.fillStyle='#34383a';x.fillRect(0,0,256,256);for(let i=0;i<5200;i++){const v=42+Math.floor(Math.random()*35);x.fillStyle=`rgba(${v},${v},${v},${.08+Math.random()*.13})`;x.fillRect(Math.random()*256,Math.random()*256,Math.random()*2+.35,Math.random()*2+.35);}for(let i=0;i<18;i++){x.strokeStyle=`rgba(8,10,12,${.025+Math.random()*.05})`;x.beginPath();x.moveTo(Math.random()*256,0);x.lineTo(Math.random()*256,256);x.stroke();}const texture=new THREE.CanvasTexture(c);texture.wrapS=texture.wrapT=THREE.RepeatWrapping;texture.repeat.set(1,1);texture.colorSpace=THREE.SRGBColorSpace;return texture;}
  private makeGantries(){for(const [index,t] of [0,.34,.67].entries()){const p=this.tp(t),tan=this.tt(t),g=new THREE.Group(),carbon=new THREE.MeshStandardMaterial({color:'#071018',metalness:.68,roughness:.26}),gold=new THREE.MeshStandardMaterial({color:index===0?'#d7a647':'#f4e8ce',emissive:index===0?'#5a3510':'#111111',emissiveIntensity:.3});for(const x of [-7,7]){const post=new THREE.Mesh(new THREE.CylinderGeometry(.13,.2,5.7,10),carbon);post.position.set(x,2.85,0);g.add(post);}const beam=new THREE.Mesh(new THREE.BoxGeometry(14.4,.58,.42),carbon);beam.position.y=5.55;g.add(beam);const panel=new THREE.Mesh(new THREE.BoxGeometry(6.3,1.18,.2),gold);panel.position.set(0,5.55,.35);g.add(panel);if(index===0)for(let i=0;i<5;i++){const light=new THREE.Mesh(new THREE.SphereGeometry(.2,12,8),new THREE.MeshStandardMaterial({color:'#321010',emissive:'#e12a2a',emissiveIntensity:.65}));light.position.set((i-2)*.62,5.48,.58);g.add(light);}g.position.set(p.x,.05,p.z);g.rotation.y=tan.yaw;g.traverse(o=>{if(o instanceof THREE.Mesh)o.castShadow=true});this.trackGroup.add(g);}}
  private makeLandscape(){
    const rockMat=new THREE.MeshStandardMaterial({color:'#a89a7d',roughness:.98}),greenMat=new THREE.MeshStandardMaterial({color:'#18582f',roughness:.96}),trunkMat=new THREE.MeshStandardMaterial({color:'#5a321c',roughness:1}),dummy=new THREE.Object3D();
    const rocks=new THREE.InstancedMesh(new THREE.ConeGeometry(1,1,7),rockMat,38);for(let i=0;i<38;i++){const a=i*.41+2.2,r=150+(i%5)*7,h=12+(i*11%28);dummy.position.set(Math.cos(a)*r,h/2-2,Math.sin(a)*r);dummy.rotation.set(0,a,0);dummy.scale.set(10+(i%4)*4,h,10+(i%4)*4);dummy.updateMatrix();rocks.setMatrixAt(i,dummy.matrix);}rocks.castShadow=!this.lowPower;rocks.receiveShadow=true;this.trackGroup.add(rocks);
    const trunks=new THREE.InstancedMesh(new THREE.CylinderGeometry(.14,.24,3.5,7),trunkMat,54),crowns=new THREE.InstancedMesh(new THREE.SphereGeometry(1,7,5),greenMat,54);for(let i=0;i<54;i++){const t=(i*.071+.08)%1,p=this.tp(t),tan=this.tt(t),side=i%2?1:-1,s=.72+(i%5)*.08,x=p.x+tan.z*(11+(i%4)*2.8)*side,z=p.z-tan.x*(11+(i%4)*2.8)*side;dummy.position.set(x,1.7*s,z);dummy.rotation.set(0,i*.8,0);dummy.scale.set(s,s,s);dummy.updateMatrix();trunks.setMatrixAt(i,dummy.matrix);dummy.position.set(x,3.7*s,z);dummy.scale.set(3.15*s,.68*s,3.15*s);dummy.updateMatrix();crowns.setMatrixAt(i,dummy.matrix);}trunks.castShadow=crowns.castShadow=!this.lowPower;this.trackGroup.add(trunks,crowns);
  }
  private makeVenue(){
    const concrete=new THREE.MeshStandardMaterial({color:'#d8cfbc',roughness:.86}),glass=new THREE.MeshPhysicalMaterial({color:'#73a7c2',roughness:.12,metalness:.2,transparent:true,opacity:.78}),terracotta=new THREE.MeshStandardMaterial({color:'#a34d32',roughness:.8}),dark=new THREE.MeshStandardMaterial({color:'#101820',roughness:.5,metalness:.32}),seatMats=['#073bbe','#d7a647','#f4e8ce'].map(color=>new THREE.MeshStandardMaterial({color,roughness:.72}));
    const safe=(x:number,z:number)=>{let best=Infinity;for(let i=0;i<180;i++){const p=this.tp(i/180);best=Math.min(best,Math.hypot(x-p.x,z-p.z));}return best>11};
    const buildingData:Array<{x:number;z:number;w:number;d:number;h:number;glass:boolean}>=[];for(let i=0;i<56;i++){const a=i*2.399,r=18+(i*17%92),x=Math.cos(a)*r+6,z=Math.sin(a)*r-2;if(!safe(x,z))continue;buildingData.push({x,z,w:4+(i%4)*1.6,d:4+(i%3),h:5+(i*13%22),glass:i%6===0});}
    const masonry=buildingData.filter(b=>!b.glass),glazed=buildingData.filter(b=>b.glass),dummy=new THREE.Object3D(),placeBuildings=(data:typeof buildingData,material:THREE.Material)=>{const mesh=new THREE.InstancedMesh(new THREE.BoxGeometry(1,1,1),material,data.length);data.forEach((b,i)=>{dummy.position.set(b.x,b.h/2,b.z);dummy.rotation.set(0,0,0);dummy.scale.set(b.w,b.h,b.d);dummy.updateMatrix();mesh.setMatrixAt(i,dummy.matrix);});mesh.castShadow=!this.lowPower;mesh.receiveShadow=true;this.trackGroup.add(mesh);};placeBuildings(masonry,concrete);placeBuildings(glazed,glass);
    const roofs=new THREE.InstancedMesh(new THREE.ConeGeometry(1,1,4),terracotta,masonry.length);masonry.forEach((b,i)=>{dummy.position.set(b.x,b.h+.7,b.z);dummy.rotation.set(0,Math.PI/4,0);dummy.scale.set(Math.max(b.w,b.d)*.62,1.5,Math.max(b.w,b.d)*.62);dummy.updateMatrix();roofs.setMatrixAt(i,dummy.matrix);});roofs.castShadow=!this.lowPower;this.trackGroup.add(roofs);
    for(const [t,side] of [[.035,-1],[.56,1],[.76,-1]] as const){const p=this.tp(t),tan=this.tt(t),stand=new THREE.Group();for(let row=0;row<7;row++){const tier=new THREE.Mesh(new THREE.BoxGeometry(20,.55,1.1),seatMats[row%3]);tier.position.set(0,.32+row*.55,row*.78);stand.add(tier);}const canopy=new THREE.Mesh(new THREE.BoxGeometry(22,.22,6.8),dark);canopy.position.set(0,6,2.7);canopy.rotation.x=-.12;stand.add(canopy);stand.position.set(p.x+tan.z*14*side,.1,p.z-tan.x*14*side);stand.rotation.y=tan.yaw+(side<0?Math.PI:0);stand.traverse(o=>{if(o instanceof THREE.Mesh)o.castShadow=true});this.trackGroup.add(stand);}
    const hulls=new THREE.InstancedMesh(new THREE.CapsuleGeometry(.55,3.2,5,10),new THREE.MeshStandardMaterial({color:'#f4e8ce',roughness:.34}),14),cabins=new THREE.InstancedMesh(new THREE.BoxGeometry(1.1,.55,1.5),glass,14),masts=new THREE.InstancedMesh(new THREE.CylinderGeometry(.025,.025,4,5),dark,14);for(let i=0;i<14;i++){const x=45+(i%5)*18,z=78+Math.floor(i/5)*14,r=-.22+(i%3)*.18;dummy.position.set(x,-2.25,z);dummy.rotation.set(Math.PI/2,r,0);dummy.scale.set(1,1,1);dummy.updateMatrix();hulls.setMatrixAt(i,dummy.matrix);dummy.position.set(x,-1.7,z-.2);dummy.rotation.set(0,r,0);dummy.updateMatrix();cabins.setMatrixAt(i,dummy.matrix);dummy.position.set(x,-.25,z);dummy.updateMatrix();masts.setMatrixAt(i,dummy.matrix);}this.trackGroup.add(hulls,cabins,masts);
    const tunnelRoof=new THREE.InstancedMesh(new THREE.BoxGeometry(14,.4,3.3),dark,10),tunnelWalls=new THREE.InstancedMesh(new THREE.BoxGeometry(.45,5.5,3.3),dark,20),lightMat=new THREE.MeshStandardMaterial({color:'#ffd890',emissive:'#ffd890',emissiveIntensity:3}),panels=new THREE.InstancedMesh(new THREE.BoxGeometry(1.5,.08,.35),lightMat,20);let wi=0,li=0;for(let i=0;i<10;i++){const t=.42+i*.004,p=this.tp(t),tan=this.tt(t);dummy.position.set(p.x,5.5,p.z);dummy.rotation.set(0,tan.yaw,0);dummy.updateMatrix();tunnelRoof.setMatrixAt(i,dummy.matrix);for(const side of [-1,1]){dummy.position.set(p.x+tan.z*6.8*side,2.7,p.z-tan.x*6.8*side);dummy.rotation.set(0,tan.yaw,0);dummy.updateMatrix();tunnelWalls.setMatrixAt(wi++,dummy.matrix);dummy.position.set(p.x+tan.z*3.8*side,5.22,p.z-tan.x*3.8*side);dummy.updateMatrix();panels.setMatrixAt(li++,dummy.matrix);}}this.trackGroup.add(tunnelRoof,tunnelWalls,panels);
    const poles=new THREE.InstancedMesh(new THREE.CylinderGeometry(.055,.08,8,7),dark,10),bulbs=new THREE.InstancedMesh(new THREE.SphereGeometry(.18,8,5),lightMat,10);let pi=0;for(const t of [.12,.28,.49,.63,.86]){const p=this.tp(t),tan=this.tt(t);for(const side of [-1,1]){const x=p.x+tan.z*8.7*side,z=p.z-tan.x*8.7*side;dummy.position.set(x,4,z);dummy.rotation.set(0,0,0);dummy.updateMatrix();poles.setMatrixAt(pi,dummy.matrix);dummy.position.set(x,7.85,z);dummy.updateMatrix();bulbs.setMatrixAt(pi++,dummy.matrix);}}this.trackGroup.add(poles,bulbs);
  }
  private makeClouds(){const mat=new THREE.MeshBasicMaterial({color:'#f4e8ce',fog:false});for(let i=0;i<(this.lowPower?6:9);i++){const g=new THREE.Group();for(let j=0;j<5;j++){const s=8+(j*7%10),m=new THREE.Mesh(new THREE.SphereGeometry(s,8,5),mat);m.scale.y=.58;m.position.set(j*8,Math.sin(j)*4,0);g.add(m);}g.position.set(-240+(i%5)*110,70+(i%3)*25,-260+Math.floor(i/5)*190);this.clouds.push(g);this.scene.add(g);}}
  private async loadCarAsset(){try{const url=new URL('models/agp01.glb',document.baseURI).href,gltf=await new GLTFLoader().loadAsync(url);this.carTemplate=gltf.scene;for(const e of this.entrants.values())this.replaceCarMesh(e);}catch(error){console.warn('AGP-01 model unavailable; retaining lightweight fallback.',error);}}
  private replaceCarMesh(e:Entrant){const previous=this.cars.get(e.id);if(!previous||!this.carTemplate)return;const position=previous.position.clone(),rotation=previous.rotation.clone();this.disposeCar(previous);const car=this.makeImportedCar(e);car.position.copy(position);car.rotation.copy(rotation);this.cars.set(e.id,car);this.scene.add(car);}
  private makeCar(e:Entrant){return buildPremiumFormulaCar(e,this.lowPower);}
  private makeImportedCar(e:Entrant){
    const g=this.carTemplate!.clone(true),palette:Record<string,string>={Body:e.colour,Secondary:e.secondary,Accent:e.accent,Carbon:'#050708',Rubber:'#020304',Metal:'#b9bec1',Visor:'#061a28'};
    g.traverse(o=>{if(!(o instanceof THREE.Mesh))return;o.geometry=o.geometry.clone();const source=Array.isArray(o.material)?o.material:[o.material];const materials=source.map(material=>{const m=material.clone() as THREE.MeshStandardMaterial;m.color.set(palette[material.name]??e.colour);if(material.name==='Body'){m.metalness=.42;m.roughness=.2;}if(material.name==='Accent')m.emissive=new THREE.Color(e.accent).multiplyScalar(.12);return m;});o.material=Array.isArray(o.material)?materials:materials[0];o.castShadow=!this.lowPower;o.receiveShadow=true;});
    const number=new THREE.Mesh(new THREE.PlaneGeometry(.86,.62),new THREE.MeshBasicMaterial({map:this.makeNumberTexture(e),transparent:true,depthWrite:false}));number.position.set(0,1.03,1.45);number.rotation.x=-Math.PI/2;g.add(number);
    const logoTexture=this.makeLogoTexture(e),logoMaterial=new THREE.MeshBasicMaterial({map:logoTexture,transparent:true,depthWrite:false,side:THREE.DoubleSide});for(const side of [-1,1]){const decal=new THREE.Mesh(new THREE.PlaneGeometry(1.65,.52),logoMaterial.clone());decal.position.set(side*1.08,.7,-.48);decal.rotation.y=side>0?Math.PI/2:-Math.PI/2;g.add(decal);}
    const identity=this.makeIdentitySprite(e);identity.position.set(0,3.15,0);g.add(identity);g.userData.wheels=[];g.scale.setScalar(.79);return g;
  }
  private makeFallbackCar(e:Entrant){
    const g=new THREE.Group(),bodyMat=new THREE.MeshPhysicalMaterial({color:e.colour,metalness:.48,roughness:.17,clearcoat:1,clearcoatRoughness:.08}),secondary=new THREE.MeshPhysicalMaterial({color:e.secondary,metalness:.3,roughness:.2,clearcoat:.8}),accent=new THREE.MeshStandardMaterial({color:e.accent,metalness:.62,roughness:.18}),carbon=new THREE.MeshStandardMaterial({color:'#07090b',roughness:.24,metalness:.74}),rubber=new THREE.MeshStandardMaterial({color:'#030405',roughness:.92}),rim=new THREE.MeshStandardMaterial({color:'#aab0b4',metalness:.95,roughness:.18});
    const add=(geo:THREE.BufferGeometry,mat:THREE.Material,x:number,y:number,z:number)=>{const m=new THREE.Mesh(geo,mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;g.add(m);return m};
    const strut=(a:THREE.Vector3,b:THREE.Vector3)=>{const d=b.clone().sub(a),m=add(new THREE.CylinderGeometry(.025,.025,d.length(),8),carbon,0,0,0);m.position.copy(a).add(b).multiplyScalar(.5);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),d.normalize());};
    add(new THREE.BoxGeometry(2.1,.08,5.6),carbon,0,.2,.15);
    const chassis=add(new THREE.CapsuleGeometry(.63,3.15,12,24),bodyMat,0,.55,.15);chassis.rotation.x=Math.PI/2;
    for(const x of [-.83,.83]){const pod=add(new THREE.CapsuleGeometry(.34,1.55,10,18),bodyMat,x,.5,-.65);pod.rotation.x=Math.PI/2;add(new THREE.BoxGeometry(.72,.12,1.95),secondary,x,.76,-.65);}
    const nose=add(new THREE.ConeGeometry(.48,3.15,10),secondary,0,.42,2.55);nose.rotation.x=Math.PI/2;
    add(new THREE.BoxGeometry(.12,.055,4.65),accent,0,.91,.25);
    add(new THREE.SphereGeometry(.48,20,12),bodyMat,0,.86,-1.38).scale.set(1,.9,1.65);
    add(new THREE.BoxGeometry(4.55,.07,.52),carbon,0,.24,3.7);add(new THREE.BoxGeometry(4.2,.05,.18),accent,0,.3,3.73);
    for(const x of [-1.94,1.94])add(new THREE.BoxGeometry(.12,.55,.56),secondary,x,.48,3.7);
    add(new THREE.BoxGeometry(3.15,.12,.68),carbon,0,1.22,-2.58);add(new THREE.BoxGeometry(2.75,.045,.7),accent,0,1.31,-2.58);
    for(const x of [-1.38,1.38])add(new THREE.BoxGeometry(.11,1.08,.16),carbon,x,.72,-2.58);
    const halo=add(new THREE.TorusGeometry(.61,.075,10,28,Math.PI*1.55),carbon,0,1.1,.18);halo.rotation.x=Math.PI/2;add(new THREE.CylinderGeometry(.055,.055,.82,10),carbon,0,1.03,.55).rotation.x=.25;
    const wheels:THREE.Mesh[]=[];for(const x of [-1.42,1.42])for(const z of [-1.7,2.05]){const w=add(new THREE.CylinderGeometry(.51,.51,.39,28),rubber,x,.48,z);w.rotation.z=Math.PI/2;wheels.push(w);const wheelRim=add(new THREE.CylinderGeometry(.27,.27,.405,20),rim,x,.48,z);wheelRim.rotation.z=Math.PI/2;const hub=add(new THREE.CylinderGeometry(.11,.11,.43,14),accent,x,.48,z);hub.rotation.z=Math.PI/2;strut(new THREE.Vector3(x*.42,.46,z-.32),new THREE.Vector3(x,.48,z));strut(new THREE.Vector3(x*.42,.46,z+.32),new THREE.Vector3(x,.48,z));}
    const numberTexture=this.makeNumberTexture(e),numberMat=new THREE.MeshBasicMaterial({map:numberTexture,transparent:true,depthWrite:false}),number=add(new THREE.PlaneGeometry(.88,.7),numberMat,0,.955,1.25);number.rotation.x=-Math.PI/2;
    const identity=this.makeIdentitySprite(e);identity.position.set(0,3.05,0);g.add(identity);
    const light=add(new THREE.BoxGeometry(.3,.12,.07),new THREE.MeshStandardMaterial({color:'#ef3232',emissive:'#ef3232',emissiveIntensity:2.8}),0,.57,-2.92);g.userData.rainLight=light;g.userData.wheels=wheels;g.scale.setScalar(.78);return g;
  }
  private makeNumberTexture(e:Entrant){const canvas=document.createElement('canvas');canvas.width=256;canvas.height=192;const ctx=canvas.getContext('2d')!;ctx.fillStyle='rgba(5,7,8,.88)';ctx.beginPath();ctx.roundRect(16,16,224,160,22);ctx.fill();ctx.strokeStyle=e.accent;ctx.lineWidth=9;ctx.stroke();ctx.fillStyle=e.secondary;ctx.font='900 116px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(String(e.number),128,101);const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;texture.anisotropy=this.renderer.capabilities.getMaxAnisotropy();return texture;}
  private makeLogoTexture(e:Entrant){const canvas=document.createElement('canvas');canvas.width=512;canvas.height=160;const c=canvas.getContext('2d')!;c.fillStyle='rgba(5,7,8,.82)';c.beginPath();c.roundRect(4,4,504,152,22);c.fill();c.strokeStyle=e.accent;c.lineWidth=5;c.stroke();c.save();c.translate(72,80);c.strokeStyle=e.secondary;c.fillStyle=e.secondary;c.lineWidth=11;c.lineCap='round';c.lineJoin='round';if(e.id==='gpt'){for(let i=0;i<6;i++){c.rotate(Math.PI/3);c.beginPath();c.arc(0,-21,27,-1.35,1.35);c.stroke();}}else if(e.id==='gemini'){c.beginPath();c.moveTo(0,-42);c.bezierCurveTo(4,-10,12,-4,42,0);c.bezierCurveTo(12,4,4,10,0,42);c.bezierCurveTo(-4,10,-12,4,-42,0);c.bezierCurveTo(-12,-4,-4,-10,0,-42);c.fill();}else if(e.id==='grok'){c.beginPath();c.moveTo(-35,-35);c.lineTo(35,35);c.moveTo(26,-38);c.lineTo(-32,37);c.stroke();}else if(e.id==='qwen'){c.beginPath();c.arc(0,0,34,0,Math.PI*2);c.stroke();c.beginPath();c.moveTo(16,22);c.lineTo(39,42);c.stroke();}else if(e.id==='deepseek'){c.beginPath();c.arc(-4,0,31,-1.5,1.5);c.stroke();c.beginPath();c.moveTo(-28,22);c.quadraticCurveTo(0,49,34,12);c.stroke();}else if(e.id==='mistral'){for(const [x,y] of [[-36,-36],[-18,-18],[0,0],[18,-18],[36,-36],[-36,-18],[-36,0],[-36,18],[36,-18],[36,0],[36,18]])c.fillRect(x-8,y-8,16,16);}else if(e.id==='llama'){c.beginPath();c.moveTo(-42,17);c.bezierCurveTo(-32,-42,-6,-42,0,0);c.bezierCurveTo(6,42,32,42,42,-17);c.bezierCurveTo(32,-42,8,-42,0,0);c.bezierCurveTo(-8,42,-32,42,-42,17);c.stroke();}else{c.font='900 64px Arial';c.textAlign='center';c.textBaseline='middle';c.fillText(e.id==='claude'?'A\\':'AI',0,3);}c.restore();c.fillStyle=e.secondary;c.font='900 52px Arial';c.textAlign='left';c.textBaseline='middle';c.fillText(e.name,132,68);c.fillStyle=e.accent;c.font='700 23px Arial';c.fillText(`${e.provider}  ·  ${String(e.number).padStart(2,'0')}`,134,112);const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;texture.anisotropy=Math.min(8,this.renderer.capabilities.getMaxAnisotropy());return texture;}
  private makeIdentitySprite(e:Entrant){const canvas=document.createElement('canvas');canvas.width=640;canvas.height=160;const ctx=canvas.getContext('2d')!;ctx.fillStyle='rgba(5,7,8,.9)';ctx.beginPath();ctx.roundRect(8,8,624,144,22);ctx.fill();ctx.fillStyle=e.colour;ctx.fillRect(8,8,20,144);ctx.fillStyle=e.accent;ctx.fillRect(28,8,8,144);ctx.fillStyle='#f4e8ce';ctx.font='800 58px Arial';ctx.textAlign='left';ctx.fillText(e.name,58,76);ctx.fillStyle='rgba(244,232,206,.68)';ctx.font='600 27px Arial';ctx.fillText(`${e.provider}  ·  #${e.number}`,60,121);const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;const material=new THREE.SpriteMaterial({map:texture,transparent:true,depthTest:false,depthWrite:false});const sprite=new THREE.Sprite(material);sprite.scale.set(5.8,1.45,1);sprite.renderOrder=20;return sprite;}
  private disposeCar(c:THREE.Group){this.scene.remove(c);c.traverse(o=>{if(o instanceof THREE.Mesh||o instanceof THREE.Sprite){if(o instanceof THREE.Mesh)o.geometry.dispose();const materials=Array.isArray(o.material)?o.material:[o.material];materials.forEach(m=>{const map=(m as THREE.MeshBasicMaterial).map;map?.dispose();m.dispose();});}});}
  private clearCars(){for(const c of this.cars.values())this.disposeCar(c);this.cars.clear();this.entrants.clear();this.drivers.clear();this.controls.clear();}
  dispose(){cancelAnimationFrame(this.raf);removeEventListener('resize',this.resize);removeEventListener('keydown',this.keyDown);removeEventListener('keyup',this.keyUp);this.raceAudio.dispose();this.premiumWeather.dispose();this.clearCars();this.renderer.dispose();this.el.removeChild(this.renderer.domElement);}
}

function lerpAngle(a:number,b:number,t:number){const d=Math.atan2(Math.sin(b-a),Math.cos(b-a));return a+d*t;}
function trackProgress(x:number,z:number,trackId:string=DEFAULT_2027_TRACK_ID){let best=0,dist=Infinity;for(let i=0;i<256;i++){const p=trackPoint(i/256,trackId),d=(p.x-x)**2+(p.z-z)**2;if(d<dist){dist=d;best=i/256;}}return best;}
