import * as THREE from 'three';
import { RaceSimulation,createCar,FIXED_DT,trackPoint,trackTangent,TRACK_WIDTH } from '@agp/sim-core';
import { DeterministicDriver,decisionToControl,observe } from '@agp/driver-sdk';
import type { Control,RaceConfig,RaceState,ReplayFile,Weather } from '@agp/shared';

export type CameraMode='broadcast'|'chase'|'cockpit'|'trackside'|'aerial';
export type SceneMode='live'|'replay'|'human';
export interface Entrant {id:string;name:string;number:number;colour:string;secondary:string;accent:string;temperament:number;provider:string;model:string;liveryTheory:string;connection:'NOT CONFIGURED'|'LOCAL'|'CONNECTED';}
export const ENTRANTS:Entrant[]=[
  {id:'gpt',name:'GPT',number:10,colour:'#101312',secondary:'#F2F1E8',accent:'#10A37F',temperament:.8,provider:'OPENAI',model:'GPT',liveryTheory:'INK AND IVORY, CUT WITH OPENAI GREEN',connection:'NOT CONFIGURED'},
  {id:'claude',name:'CLAUDE',number:32,colour:'#D97757',secondary:'#F1E8D7',accent:'#1E1D1B',temperament:.35,provider:'ANTHROPIC',model:'CLAUDE',liveryTheory:'TERRACOTTA, WARM PAPER AND QUIET INK',connection:'NOT CONFIGURED'},
  {id:'gemini',name:'GEMINI',number:88,colour:'#4285F4',secondary:'#A142F4',accent:'#F4E8CE',temperament:.55,provider:'GOOGLE',model:'GEMINI',liveryTheory:'GOOGLE BLUE FLOWING INTO GEMINI VIOLET',connection:'NOT CONFIGURED'},
  {id:'grok',name:'GROK',number:24,colour:'#050708',secondary:'#F4E8CE',accent:'#8A9298',temperament:.9,provider:'xAI',model:'GROK',liveryTheory:'BLACK MONOLITH, IVORY TYPE AND STEEL DETAIL',connection:'NOT CONFIGURED'},
  {id:'qwen',name:'QWEN',number:72,colour:'#615CED',secondary:'#38D4FF',accent:'#F4E8CE',temperament:.15,provider:'ALIBABA CLOUD',model:'QWEN',liveryTheory:'QWEN VIOLET WITH DIGITAL CYAN SIGNALS',connection:'NOT CONFIGURED'},
  {id:'deepseek',name:'DEEPSEEK',number:1,colour:'#4D6BFE',secondary:'#EAF0FF',accent:'#15286B',temperament:-.1,provider:'DEEPSEEK',model:'DEEPSEEK',liveryTheory:'ELECTRIC BLUE, ICE WHITE AND DEEP NAVY',connection:'NOT CONFIGURED'},
  {id:'mistral',name:'MISTRAL',number:7,colour:'#F97316',secondary:'#FFCF59',accent:'#071018',temperament:.65,provider:'MISTRAL AI',model:'MISTRAL',liveryTheory:'HOT ORANGE AND AMBER OVER CARBON BLACK',connection:'NOT CONFIGURED'},
  {id:'llama',name:'LLAMA',number:70,colour:'#0668E1',secondary:'#F4E8CE',accent:'#00C2FF',temperament:-.35,provider:'META',model:'LLAMA',liveryTheory:'META BLUE WITH CLEAN IVORY AND CYAN',connection:'NOT CONFIGURED'}
];

export class GrandPrixScene{
  private scene=new THREE.Scene();private camera=new THREE.PerspectiveCamera(42,1,.1,1200);private renderer:THREE.WebGLRenderer;private sim!:RaceSimulation;private drivers=new Map<string,DeterministicDriver>();private controls=new Map<string,Control>();private cars=new Map<string,THREE.Group>();private raf=0;private last=0;private acc=0;private paused=true;private mode:CameraMode='broadcast';private sceneMode:SceneMode='live';private emitAt=0;private resize:()=>void;private focusId='gpt';private playbackSpeed=1;private replay:ReplayFile|null=null;private replayTime=0;private replayDuration=0;private keys=new Set<string>();private touch={left:false,right:false,gas:false,brake:false,boost:false};private clouds:THREE.Group[]=[];private water!:THREE.Mesh;private weather:Weather='CLEAR';private audio:AudioContext|null=null;private oscillator:OscillatorNode|null=null;private audioGain:GainNode|null=null;
  constructor(private el:HTMLElement,private onState:(s:RaceState)=>void,private onReplayProgress?:(time:number,duration:number)=>void){
    this.renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.16;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;el.appendChild(this.renderer.domElement);
    this.resize=()=>{this.camera.aspect=Math.max(.2,el.clientWidth/el.clientHeight);this.camera.updateProjectionMatrix();this.renderer.setSize(el.clientWidth,el.clientHeight,false)};addEventListener('resize',this.resize);addEventListener('keydown',this.keyDown);addEventListener('keyup',this.keyUp);this.resize();this.buildWorld();this.startRace({session:'QUICK_RACE',laps:3,entrants:8,weather:'CLEAR',seed:4127});
  }
  private keyDown=(e:KeyboardEvent)=>{this.keys.add(e.code);};private keyUp=(e:KeyboardEvent)=>{this.keys.delete(e.code);};
  startRace(config:RaceConfig){this.clearCars();this.sceneMode=config.session==='HUMAN_TEST'?'human':'live';this.replay=null;this.replayTime=0;this.weather=config.weather;this.applyWeather();const selected=ENTRANTS.slice(0,Math.max(1,Math.min(config.entrants,ENTRANTS.length)));if(this.sceneMode==='human')selected[0]={...selected[0],id:'human',name:'HUMAN TEST',number:99,colour:'#F4E8CE',secondary:'#073BBE',accent:'#D7A647',provider:'AGP',model:'HUMAN INPUT',liveryTheory:'IVORY AND COBALT AGP DEVELOPMENT LIVERY',connection:'LOCAL'};const states=selected.map((e,i)=>createCar(e.id,e.name,e.number,e.colour,i));this.sim=new RaceSimulation(states,config.laps,config.seed,config.weather);for(const e of selected){if(e.id!=='human')this.drivers.set(e.id,new DeterministicDriver(e.id,e.name,e.temperament));const mesh=this.makeCar(e);this.cars.set(e.id,mesh);this.scene.add(mesh);}this.focusId=selected[0].id;this.paused=false;this.updateMeshes();this.onState(this.sim.state);}
  async loadReplay(replay:ReplayFile){this.clearCars();this.sceneMode='replay';this.replay=replay;this.replayTime=0;this.replayDuration=replay.frames.at(-1)?.t??0;this.paused=false;this.weather='CLEAR';this.applyWeather();const first=replay.frames[0];if(!first)throw new Error('Replay has no frames');const entrants=first.cars.map((c,i)=>ENTRANTS.find(e=>e.id===c.id)??{...ENTRANTS[i%ENTRANTS.length],id:c.id,name:c.id.toUpperCase()});const states=entrants.map((e,i)=>createCar(e.id,e.name,e.number,e.colour,i));this.sim=new RaceSimulation(states,replay.laps,replay.seed);for(const e of entrants){const mesh=this.makeCar(e);this.cars.set(e.id,mesh);this.scene.add(mesh);}this.focusId=entrants[0].id;this.applyReplayFrame(0);}
  restart(){if(this.replay){void this.loadReplay(this.replay);}else this.startRace({session:this.sceneMode==='human'?'HUMAN_TEST':'QUICK_RACE',laps:this.sim.laps,entrants:this.sim.state.cars.length,weather:this.weather,seed:this.sim.state.seed});}
  setCamera(m:CameraMode){this.mode=m;}setPaused(v:boolean){this.paused=v;}setFocus(id:string){if(this.cars.has(id))this.focusId=id;}setPlaybackSpeed(v:number){this.playbackSpeed=Math.max(.25,Math.min(4,v));}setHumanControl(key:keyof typeof this.touch,active:boolean){this.touch[key]=active;}async setSound(enabled:boolean){if(enabled){this.audio??=new AudioContext();await this.audio.resume();if(!this.oscillator){this.oscillator=this.audio.createOscillator();this.audioGain=this.audio.createGain();this.oscillator.type='sawtooth';this.audioGain.gain.value=.025;this.oscillator.connect(this.audioGain).connect(this.audio.destination);this.oscillator.start();}}else if(this.audioGain)this.audioGain.gain.setTargetAtTime(0,this.audio!.currentTime,.04);}seekReplay(seconds:number){if(!this.replay)return;this.replayTime=Math.max(0,Math.min(this.replayDuration,seconds));this.applyReplayFrame(this.replayTime);}
  start(){this.last=performance.now();const frame=(now:number)=>{const delta=Math.min((now-this.last)/1000,.05);this.last=now;if(!this.paused){if(this.sceneMode==='replay'&&this.replay){this.replayTime=Math.min(this.replayDuration,this.replayTime+delta*this.playbackSpeed);this.applyReplayFrame(this.replayTime);if(this.replayTime>=this.replayDuration)this.paused=true;}else{this.acc+=delta;while(this.acc>=FIXED_DT){this.tickDrivers();this.sim.step(this.controls,FIXED_DT);this.acc-=FIXED_DT;}this.updateMeshes();}}this.animateWorld(now/1000);this.updateCamera(now/1000);this.renderer.render(this.scene,this.camera);if(now>this.emitAt){this.emitAt=now+100;this.onState(this.sim.state);if(this.replay)this.onReplayProgress?.(this.replayTime,this.replayDuration);}this.raf=requestAnimationFrame(frame)};this.raf=requestAnimationFrame(frame);}
  private humanControl():Control{const left=this.keys.has('ArrowLeft')||this.keys.has('KeyA')||this.touch.left,right=this.keys.has('ArrowRight')||this.keys.has('KeyD')||this.touch.right,gas=this.keys.has('ArrowUp')||this.keys.has('KeyW')||this.touch.gas,brake=this.keys.has('ArrowDown')||this.keys.has('KeyS')||this.touch.brake;return{steering:(left?-1:0)+(right?1:0),throttle:gas?1:0,brake:brake?1:0,energyDeploy:this.keys.has('Space')||this.touch.boost?1:0};}
  private tickDrivers(){if(this.sceneMode==='human')this.controls.set('human',this.humanControl());if(this.sim.state.tick%30!==0)return;for(const car of this.sim.state.cars){const d=this.drivers.get(car.id);if(!d)continue;void d.decide(observe(this.sim.state,car)).then(x=>this.controls.set(car.id,decisionToControl(x)));}}
  private applyReplayFrame(time:number){if(!this.replay)return;let lo=0,hi=this.replay.frames.length-1;while(lo<hi){const mid=Math.floor((lo+hi+1)/2);if(this.replay.frames[mid].t<=time)lo=mid;else hi=mid-1;}const a=this.replay.frames[lo],b=this.replay.frames[Math.min(lo+1,this.replay.frames.length-1)],mix=a===b?0:(time-a.t)/(b.t-a.t);for(const car of this.sim.state.cars){const x=a.cars.find(c=>c.id===car.id),y=b.cars.find(c=>c.id===car.id)??x;if(!x||!y)continue;car.x=THREE.MathUtils.lerp(x.x,y.x,mix);car.z=THREE.MathUtils.lerp(x.z,y.z,mix);car.yaw=lerpAngle(x.yaw,y.yaw,mix);car.speed=THREE.MathUtils.lerp(x.speed,y.speed,mix);car.lap=x.lap;car.position=x.position;car.status=x.status;car.progress=trackProgress(car.x,car.z);}this.sim.state.time=time;this.sim.state.tick=Math.round(time/FIXED_DT);this.sim.state.flag=time>=this.replayDuration?'CHEQUERED':'GREEN';this.updateMeshes();this.onState(this.sim.state);}
  private updateMeshes(){for(const s of this.sim.state.cars){const g=this.cars.get(s.id);if(!g)continue;g.position.set(s.x,.72,s.z);g.rotation.y=s.yaw;const wheels=g.userData.wheels as THREE.Mesh[];wheels.forEach((w,i)=>{w.rotation.x-=s.speed*FIXED_DT/.38;if(i<2)w.rotation.y=s.controls.steering*.35;});const rain=g.userData.rainLight as THREE.Mesh|undefined;if(rain)(rain.material as THREE.MeshStandardMaterial).emissiveIntensity=1.5+Math.sin(this.sim.state.time*12)*1.2;}}
  private updateCamera(t:number){const targetCar=this.sim.state.cars.find(c=>c.id===this.focusId)??[...this.sim.state.cars].sort((a,b)=>a.position-b.position)[0];if(!targetCar)return;const target=new THREE.Vector3(targetCar.x,1.1,targetCar.z),forward=new THREE.Vector3(Math.sin(targetCar.yaw),0,Math.cos(targetCar.yaw));if(this.mode==='chase'){this.camera.position.lerp(target.clone().addScaledVector(forward,-11).add(new THREE.Vector3(0,4.2,0)),.08);this.camera.lookAt(target.clone().addScaledVector(forward,8));}else if(this.mode==='cockpit'){this.camera.position.lerp(target.clone().addScaledVector(forward,.15).add(new THREE.Vector3(0,.55,0)),.35);this.camera.lookAt(target.clone().addScaledVector(forward,30));}else if(this.mode==='aerial'){this.camera.position.lerp(new THREE.Vector3(targetCar.x+4,58,targetCar.z+7),.035);this.camera.lookAt(target);}else if(this.mode==='trackside'){const p=trackPoint((targetCar.progress+.025)%1),tan=trackTangent((targetCar.progress+.025)%1);this.camera.position.lerp(new THREE.Vector3(p.x+tan.z*12,5,p.z-tan.x*12),.045);this.camera.lookAt(target);}else{const cuts=[new THREE.Vector3(-150,20,-45),new THREE.Vector3(44,13,-122),new THREE.Vector3(154,17,34),new THREE.Vector3(-18,11,112)];const c=cuts[Math.floor((this.sim.state.time/8)%cuts.length)];this.camera.position.lerp(c,.02);this.camera.lookAt(target.clone().add(new THREE.Vector3(0,0,Math.sin(t*.3)*1.4)));}}
  private buildWorld(){this.scene.background=new THREE.Color('#073bbe');this.scene.fog=new THREE.FogExp2('#6e9cdf',.00145);this.scene.add(new THREE.HemisphereLight('#cbe0ff','#08120b',2.2));const sun=new THREE.DirectionalLight('#ffe9bd',5);sun.position.set(-90,140,-70);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-210;sun.shadow.camera.right=210;sun.shadow.camera.top=180;sun.shadow.camera.bottom=-180;this.scene.add(sun);this.water=new THREE.Mesh(new THREE.CircleGeometry(520,96),new THREE.MeshStandardMaterial({color:'#064fa0',roughness:.16,metalness:.24}));this.water.rotation.x=-Math.PI/2;this.water.position.y=-3.2;this.water.receiveShadow=true;this.scene.add(this.water);const island=new THREE.Mesh(new THREE.CylinderGeometry(176,215,12,80),new THREE.MeshStandardMaterial({color:'#d8c8a6',roughness:.88}));island.position.y=-5.5;island.receiveShadow=true;this.scene.add(island);this.makeRoad();this.makeLandscape();this.makeClouds();}
  private applyWeather(){this.scene.fog=new THREE.FogExp2(this.weather==='RAIN'?'#60758a':this.weather==='OVERCAST'?'#8296a9':'#6e9cdf',this.weather==='RAIN'?.0032:.00145);this.renderer.toneMappingExposure=this.weather==='RAIN'?.83:this.weather==='OVERCAST'?.98:1.16;}
  private animateWorld(t:number){this.clouds.forEach((c,i)=>{c.position.x+=.002*(i%3+1);c.rotation.y=Math.sin(t*.015+i)*.02;});this.water.rotation.z=Math.sin(t*.07)*.002;const car=this.sim.state.cars.find(c=>c.id===this.focusId);if(this.oscillator&&this.audioGain&&this.audio){this.oscillator.frequency.setTargetAtTime(55+(car?.speed??0)*5.3,this.audio.currentTime,.03);this.audioGain.gain.setTargetAtTime(this.paused ? .008 : .025,this.audio.currentTime,.06);}}
  private makeRoad(){const count=720,pos:number[]=[],idx:number[]=[];for(let i=0;i<=count;i++){const t=(i%count)/count,p=trackPoint(t),tan=trackTangent(t),nx=tan.z,nz=-tan.x;pos.push(p.x+nx*TRACK_WIDTH/2,.06,p.z+nz*TRACK_WIDTH/2,p.x-nx*TRACK_WIDTH/2,.06,p.z-nz*TRACK_WIDTH/2);if(i<count){const a=i*2;idx.push(a,a+1,a+2,a+1,a+3,a+2);}}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));geo.setIndex(idx);geo.computeVertexNormals();const road=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color:'#111a1e',roughness:.78,metalness:.06}));road.receiveShadow=true;this.scene.add(road);for(let i=0;i<144;i++){const t=i/144,p=trackPoint(t),tan=trackTangent(t);for(const side of [-1,1]){const kerb=new THREE.Mesh(new THREE.BoxGeometry(.68,.13,2.45),new THREE.MeshStandardMaterial({color:i%2?'#f4e8ce':'#073bbe'}));kerb.position.set(p.x+tan.z*6.35*side,.13,p.z-tan.x*6.35*side);kerb.rotation.y=tan.yaw;kerb.castShadow=true;this.scene.add(kerb);}}const start=trackPoint(0),st=trackTangent(0);for(let i=0;i<10;i++){const mark=new THREE.Mesh(new THREE.BoxGeometry(.78,.025,1),new THREE.MeshBasicMaterial({color:i%2?'#071018':'#f4e8ce'}));mark.position.set(start.x+st.z*(i-5)*1.5,.1,start.z-st.x*(i-5)*1.5);mark.rotation.y=st.yaw;this.scene.add(mark);}this.makeGantries();}
  private makeGantries(){for(const t of [0,.33,.66]){const p=trackPoint(t),tan=trackTangent(t),g=new THREE.Group(),mat=new THREE.MeshStandardMaterial({color:'#071018',metalness:.55,roughness:.38});for(const x of [-7.4,7.4]){const post=new THREE.Mesh(new THREE.BoxGeometry(.28,5,.28),mat);post.position.set(x,2.5,0);g.add(post);}const beam=new THREE.Mesh(new THREE.BoxGeometry(15,.65,.35),mat);beam.position.y=5;g.add(beam);const panel=new THREE.Mesh(new THREE.BoxGeometry(5.8,1.2,.18),new THREE.MeshStandardMaterial({color:t===0?'#d7a647':'#f4e8ce'}));panel.position.set(0,5,.25);g.add(panel);g.position.set(p.x,.05,p.z);g.rotation.y=tan.yaw;g.traverse(o=>{if(o instanceof THREE.Mesh)o.castShadow=true});this.scene.add(g);}}
  private makeLandscape(){const rockMat=new THREE.MeshStandardMaterial({color:'#ccb98f',roughness:.95}),greenMat=new THREE.MeshStandardMaterial({color:'#174a24',roughness:.98}),trunkMat=new THREE.MeshStandardMaterial({color:'#2b1c12'});for(let i=0;i<52;i++){const a=i*2.399,r=135+(i%5)*8,h=8+(i*7%19),rock=new THREE.Mesh(new THREE.ConeGeometry(9+(i%4)*3,h,6),rockMat);rock.position.set(Math.cos(a)*r,h/2-1,Math.sin(a)*r);rock.rotation.y=a;rock.castShadow=true;rock.receiveShadow=true;this.scene.add(rock);}const trunk=new THREE.CylinderGeometry(.18,.28,2.3,5),crown=new THREE.ConeGeometry(1.7,4.8,7);for(let i=0;i<125;i++){const a=i*1.827,r=35+(i*31%125),x=Math.cos(a)*r,z=Math.sin(a)*r;if(Math.abs(Math.hypot(x/116,z/72)-1)<.12)continue;const tree=new THREE.Group(),tr=new THREE.Mesh(trunk,trunkMat),cr=new THREE.Mesh(crown,greenMat);tr.position.y=1;cr.position.y=4;tree.add(tr,cr);tree.position.set(x,0,z);tree.scale.setScalar(.65+(i%7)*.08);tree.rotation.y=a;tree.children.forEach(m=>m.castShadow=true);this.scene.add(tree);}for(let i=0;i<22;i++){const a=i*.43,x=-20+Math.cos(a)*27,z=5+Math.sin(a)*20,b=new THREE.Mesh(new THREE.BoxGeometry(4+(i%3),3+(i%4),4),new THREE.MeshStandardMaterial({color:'#eadcbc',roughness:.9}));b.position.set(x,b.geometry.parameters.height/2,z);b.castShadow=true;this.scene.add(b);const roof=new THREE.Mesh(new THREE.ConeGeometry(3.8,1.4,4),new THREE.MeshStandardMaterial({color:'#a1452d'}));roof.position.set(x,b.geometry.parameters.height+.6,z);roof.rotation.y=Math.PI/4;roof.castShadow=true;this.scene.add(roof);}}
  private makeClouds(){const mat=new THREE.MeshBasicMaterial({color:'#f4e8ce',fog:false});for(let i=0;i<13;i++){const g=new THREE.Group();for(let j=0;j<7;j++){const s=8+(j*7%10),m=new THREE.Mesh(new THREE.SphereGeometry(s,10,7),mat);m.scale.y=.58;m.position.set(j*8,Math.sin(j)*4,0);g.add(m);}g.position.set(-240+(i%5)*110,70+(i%3)*25,-260+Math.floor(i/5)*190);this.clouds.push(g);this.scene.add(g);}}
  private makeCar(e:Entrant){
    const g=new THREE.Group(),bodyMat=new THREE.MeshPhysicalMaterial({color:e.colour,metalness:.48,roughness:.17,clearcoat:1,clearcoatRoughness:.08}),secondary=new THREE.MeshPhysicalMaterial({color:e.secondary,metalness:.3,roughness:.2,clearcoat:.8}),accent=new THREE.MeshStandardMaterial({color:e.accent,metalness:.62,roughness:.18}),carbon=new THREE.MeshStandardMaterial({color:'#07090b',roughness:.24,metalness:.74}),rubber=new THREE.MeshStandardMaterial({color:'#030405',roughness:.92}),rim=new THREE.MeshStandardMaterial({color:'#aab0b4',metalness:.95,roughness:.18});
    const add=(geo:THREE.BufferGeometry,mat:THREE.Material,x:number,y:number,z:number)=>{const m=new THREE.Mesh(geo,mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;g.add(m);return m};
    const strut=(a:THREE.Vector3,b:THREE.Vector3)=>{const d=b.clone().sub(a),m=add(new THREE.CylinderGeometry(.025,.025,d.length(),8),carbon,0,0,0);m.position.copy(a).add(b).multiplyScalar(.5);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),d.normalize());};
    add(new THREE.BoxGeometry(2.1,.08,5.6),carbon,0,.2,.15);
    const chassis=add(new THREE.CapsuleGeometry(.63,3.15,12,24),bodyMat,0,.55,.15);chassis.rotation.x=Math.PI/2;
    for(const x of [-.83,.83]){const pod=add(new THREE.CapsuleGeometry(.34,1.55,10,18),bodyMat,x,.5,-.65);pod.rotation.x=Math.PI/2;add(new THREE.BoxGeometry(.72,.12,1.95),secondary,x,.76,-.65);}
    const nose=add(new THREE.ConeGeometry(.48,3.15,10),secondary,0,.42,2.55);nose.rotation.x=Math.PI/2;
    add(new THREE.BoxGeometry(.12,.055,4.65),accent,0,.91,.25);
    add(new THREE.SphereGeometry(.48,20,12),bodyMat,0,.86,-1.38).scale.set(1,.9,1.65);
    add(new THREE.BoxGeometry(4.55,.07,.52),carbon,0,.24,3.7);add(new THREE.BoxGeometry(4.2,.05,.18),accent,0,.3,3.73);
    for(const x of [-1.94,1.94])add(new THREE.BoxGeometry(.12,.55,.56),secondary,x,.48,3.7);
    add(new THREE.BoxGeometry(3.15,.12,.68),carbon,0,1.22,-2.58);add(new THREE.BoxGeometry(2.75,.045,.7),accent,0,1.31,-2.58);
    for(const x of [-1.38,1.38])add(new THREE.BoxGeometry(.11,1.08,.16),carbon,x,.72,-2.58);
    const halo=add(new THREE.TorusGeometry(.61,.075,10,28,Math.PI*1.55),carbon,0,1.1,.18);halo.rotation.x=Math.PI/2;add(new THREE.CylinderGeometry(.055,.055,.82,10),carbon,0,1.03,.55).rotation.x=.25;
    const wheels:THREE.Mesh[]=[];for(const x of [-1.42,1.42])for(const z of [-1.7,2.05]){const w=add(new THREE.CylinderGeometry(.51,.51,.39,28),rubber,x,.48,z);w.rotation.z=Math.PI/2;wheels.push(w);const wheelRim=add(new THREE.CylinderGeometry(.27,.27,.405,20),rim,x,.48,z);wheelRim.rotation.z=Math.PI/2;const hub=add(new THREE.CylinderGeometry(.11,.11,.43,14),accent,x,.48,z);hub.rotation.z=Math.PI/2;strut(new THREE.Vector3(x*.42,.46,z-.32),new THREE.Vector3(x,.48,z));strut(new THREE.Vector3(x*.42,.46,z+.32),new THREE.Vector3(x,.48,z));}
    const numberTexture=this.makeNumberTexture(e),numberMat=new THREE.MeshBasicMaterial({map:numberTexture,transparent:true,depthWrite:false}),number=add(new THREE.PlaneGeometry(.88,.7),numberMat,0,.955,1.25);number.rotation.x=-Math.PI/2;
    const identity=this.makeIdentitySprite(e);identity.position.set(0,3.05,0);g.add(identity);
    const light=add(new THREE.BoxGeometry(.3,.12,.07),new THREE.MeshStandardMaterial({color:'#ef3232',emissive:'#ef3232',emissiveIntensity:2.8}),0,.57,-2.92);g.userData.rainLight=light;g.userData.wheels=wheels;g.scale.setScalar(.78);return g;
  }
  private makeNumberTexture(e:Entrant){const canvas=document.createElement('canvas');canvas.width=256;canvas.height=192;const ctx=canvas.getContext('2d')!;ctx.fillStyle='rgba(5,7,8,.88)';ctx.beginPath();ctx.roundRect(16,16,224,160,22);ctx.fill();ctx.strokeStyle=e.accent;ctx.lineWidth=9;ctx.stroke();ctx.fillStyle=e.secondary;ctx.font='900 116px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(String(e.number),128,101);const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;texture.anisotropy=this.renderer.capabilities.getMaxAnisotropy();return texture;}
  private makeIdentitySprite(e:Entrant){const canvas=document.createElement('canvas');canvas.width=640;canvas.height=160;const ctx=canvas.getContext('2d')!;ctx.fillStyle='rgba(5,7,8,.9)';ctx.beginPath();ctx.roundRect(8,8,624,144,22);ctx.fill();ctx.fillStyle=e.colour;ctx.fillRect(8,8,20,144);ctx.fillStyle=e.accent;ctx.fillRect(28,8,8,144);ctx.fillStyle='#f4e8ce';ctx.font='800 58px Arial';ctx.textAlign='left';ctx.fillText(e.name,58,76);ctx.fillStyle='rgba(244,232,206,.68)';ctx.font='600 27px Arial';ctx.fillText(`${e.provider}  ·  #${e.number}`,60,121);const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;const material=new THREE.SpriteMaterial({map:texture,transparent:true,depthTest:false,depthWrite:false});const sprite=new THREE.Sprite(material);sprite.scale.set(5.8,1.45,1);sprite.renderOrder=20;return sprite;}
  private clearCars(){for(const c of this.cars.values()){this.scene.remove(c);c.traverse(o=>{if(o instanceof THREE.Mesh||o instanceof THREE.Sprite){if(o instanceof THREE.Mesh)o.geometry.dispose();const materials=Array.isArray(o.material)?o.material:[o.material];materials.forEach(m=>{const map=(m as THREE.MeshBasicMaterial).map;map?.dispose();m.dispose();});}});}this.cars.clear();this.drivers.clear();this.controls.clear();}
  dispose(){cancelAnimationFrame(this.raf);removeEventListener('resize',this.resize);removeEventListener('keydown',this.keyDown);removeEventListener('keyup',this.keyUp);this.oscillator?.stop();void this.audio?.close();this.clearCars();this.renderer.dispose();this.el.removeChild(this.renderer.domElement);}
}

function lerpAngle(a:number,b:number,t:number){const d=Math.atan2(Math.sin(b-a),Math.cos(b-a));return a+d*t;}
function trackProgress(x:number,z:number){let best=0,dist=Infinity;for(let i=0;i<180;i++){const p=trackPoint(i/180),d=(p.x-x)**2+(p.z-z)**2;if(d<dist){dist=d;best=i/180;}}return best;}
