import * as THREE from 'three';
import { RaceSimulation,createCar,FIXED_DT,trackPoint,trackTangent,TRACK_WIDTH } from '@agp/sim-core';
import { DeterministicDriver,decisionToControl,observe } from '@agp/driver-sdk';
import type { Control,RaceState } from '@agp/shared';
export type CameraMode='broadcast'|'chase'|'aerial';

const entrants=[['apex','APEX LOGIC',7,'#d7a647',.8],['vector','VECTOR MIND',12,'#f4e8ce',0],['neural','NEURAL WORKS',27,'#d62828',-.6],['synthesis','SYNTHESIS',44,'#23a9ff',.35]] as const;
export class GrandPrixScene{
  private scene=new THREE.Scene();private camera=new THREE.PerspectiveCamera(42,1,.1,1200);private renderer:THREE.WebGLRenderer;private sim!:RaceSimulation;private drivers=new Map<string,DeterministicDriver>();private controls=new Map<string,Control>();private cars=new Map<string,THREE.Group>();private raf=0;private last=0;private acc=0;private paused=false;private mode:CameraMode='broadcast';private emitAt=0;private resize:()=>void;
  constructor(private el:HTMLElement,private onState:(s:RaceState)=>void){
    this.renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.18;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;el.appendChild(this.renderer.domElement);this.resize=()=>{this.camera.aspect=el.clientWidth/el.clientHeight;this.camera.updateProjectionMatrix();this.renderer.setSize(el.clientWidth,el.clientHeight,false)};addEventListener('resize',this.resize);this.resize();this.buildWorld();this.restart();
  }
  restart(){for(const c of this.cars.values())this.scene.remove(c);this.cars.clear();this.drivers.clear();this.controls.clear();const states=entrants.map((e,i)=>createCar(e[0],e[1],e[2],e[3],i));this.sim=new RaceSimulation(states,3,4127);entrants.forEach(e=>{this.drivers.set(e[0],new DeterministicDriver(e[0],e[1],e[4]));const mesh=this.makeCar(e[3],e[2]);this.cars.set(e[0],mesh);this.scene.add(mesh);});this.updateMeshes();this.onState(this.sim.state);}
  setCamera(m:CameraMode){this.mode=m;}setPaused(v:boolean){this.paused=v;}
  start(){this.last=performance.now();const frame=(now:number)=>{const delta=Math.min((now-this.last)/1000,.05);this.last=now;if(!this.paused){this.acc+=delta;while(this.acc>=FIXED_DT){this.tickDrivers();this.sim.step(this.controls,FIXED_DT);this.acc-=FIXED_DT;}this.updateMeshes();}this.updateCamera(now/1000);this.renderer.render(this.scene,this.camera);if(now>this.emitAt){this.emitAt=now+120;this.onState(this.sim.state);}this.raf=requestAnimationFrame(frame)};this.raf=requestAnimationFrame(frame);}
  private tickDrivers(){if(this.sim.state.tick%30!==0)return;for(const car of this.sim.state.cars){const d=this.drivers.get(car.id);if(!d)continue;void d.decide(observe(this.sim.state,car)).then(x=>this.controls.set(car.id,decisionToControl(x)));}}
  private updateMeshes(){for(const s of this.sim.state.cars){const g=this.cars.get(s.id);if(!g)continue;g.position.set(s.x,.72,s.z);g.rotation.y=s.yaw;const wheels=g.userData.wheels as THREE.Mesh[];wheels.forEach((w,i)=>{w.rotation.x-=s.speed*FIXED_DT/.38;if(i<2)w.rotation.y=s.controls.steering*.35;});}}
  private updateCamera(t:number){const lead=[...this.sim.state.cars].sort((a,b)=>a.position-b.position)[0];if(!lead)return;const target=new THREE.Vector3(lead.x,1.2,lead.z);if(this.mode==='chase'){const behind=new THREE.Vector3(-Math.sin(lead.yaw)*10,4,-Math.cos(lead.yaw)*10);this.camera.position.lerp(target.clone().add(behind),.065);this.camera.lookAt(target);}else if(this.mode==='aerial'){this.camera.position.lerp(new THREE.Vector3(lead.x+3,60,lead.z+5),.025);this.camera.lookAt(target);}else{const cuts=[new THREE.Vector3(-150,22,-45),new THREE.Vector3(40,14,-120),new THREE.Vector3(155,18,30),new THREE.Vector3(-15,12,112)];const c=cuts[Math.floor((this.sim.state.time/9)%cuts.length)];this.camera.position.lerp(c,.018);this.camera.lookAt(target.clone().add(new THREE.Vector3(0,0,Math.sin(t*.3)*2)));}}
  private buildWorld(){
    this.scene.background=new THREE.Color('#073bbe');this.scene.fog=new THREE.FogExp2('#6e9cdf',.00145);
    const hemi=new THREE.HemisphereLight('#bcd8ff','#08120b',2.2);this.scene.add(hemi);const sun=new THREE.DirectionalLight('#ffe9bd',5);sun.position.set(-90,140,-70);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-210;sun.shadow.camera.right=210;sun.shadow.camera.top=180;sun.shadow.camera.bottom=-180;this.scene.add(sun);
    const sea=new THREE.Mesh(new THREE.CircleGeometry(520,96),new THREE.MeshStandardMaterial({color:'#064fa0',roughness:.18,metalness:.22}));sea.rotation.x=-Math.PI/2;sea.position.y=-3.2;sea.receiveShadow=true;this.scene.add(sea);
    const island=new THREE.Mesh(new THREE.CylinderGeometry(176,215,12,80),new THREE.MeshStandardMaterial({color:'#d8c8a6',roughness:.88}));island.position.y=-5.5;island.receiveShadow=true;this.scene.add(island);
    this.makeRoad();this.makeLandscape();this.makeClouds();
  }
  private makeRoad(){const count=720,pos:number[]=[],idx:number[]=[];for(let i=0;i<=count;i++){const t=(i%count)/count,p=trackPoint(t),tan=trackTangent(t),nx=tan.z,nz=-tan.x;pos.push(p.x+nx*TRACK_WIDTH/2,.06,p.z+nz*TRACK_WIDTH/2,p.x-nx*TRACK_WIDTH/2,.06,p.z-nz*TRACK_WIDTH/2);if(i<count){const a=i*2;idx.push(a,a+1,a+2,a+1,a+3,a+2);}}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));geo.setIndex(idx);geo.computeVertexNormals();const road=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color:'#111a1e',roughness:.78,metalness:.06}));road.receiveShadow=true;this.scene.add(road);
    for(let i=0;i<96;i++){const t=i/96,p=trackPoint(t),tan=trackTangent(t),kerb=new THREE.Mesh(new THREE.BoxGeometry(.8,.13,3.4),new THREE.MeshStandardMaterial({color:i%2?'#f4e8ce':'#073bbe'}));kerb.position.set(p.x+tan.z*6.2,.13,p.z-tan.x*6.2);kerb.rotation.y=tan.yaw;kerb.castShadow=true;this.scene.add(kerb);}
    const start=trackPoint(0),st=trackTangent(0);for(let i=0;i<10;i++){const mark=new THREE.Mesh(new THREE.BoxGeometry(i%2?.75:.75,.025,1),new THREE.MeshBasicMaterial({color:i%2?'#071018':'#f4e8ce'}));mark.position.set(start.x+st.z*(i-5)*1.5,.1,start.z-st.x*(i-5)*1.5);mark.rotation.y=st.yaw;this.scene.add(mark);}
  }
  private makeLandscape(){const rockMat=new THREE.MeshStandardMaterial({color:'#ccb98f',roughness:.95});const greenMat=new THREE.MeshStandardMaterial({color:'#174a24',roughness:.98});for(let i=0;i<46;i++){const a=i*2.399,r=135+(i%5)*8,h=8+(i*7%19),rock=new THREE.Mesh(new THREE.ConeGeometry(9+(i%4)*3,h,6),rockMat);rock.position.set(Math.cos(a)*r,h/2-1,Math.sin(a)*r);rock.rotation.y=a;rock.castShadow=true;rock.receiveShadow=true;this.scene.add(rock);}
    const trunk=new THREE.CylinderGeometry(.18,.28,2.3,5),crown=new THREE.ConeGeometry(1.7,4.8,7);for(let i=0;i<115;i++){const a=i*1.827,r=35+(i*31%125),x=Math.cos(a)*r,z=Math.sin(a)*r;if(Math.abs(Math.hypot(x/116,z/72)-1)<.12)continue;const tree=new THREE.Group(),tr=new THREE.Mesh(trunk,new THREE.MeshStandardMaterial({color:'#2b1c12'})),cr=new THREE.Mesh(crown,greenMat);tr.position.y=1;cr.position.y=4;tree.add(tr,cr);tree.position.set(x,0,z);tree.scale.setScalar(.65+(i%7)*.08);tree.rotation.y=a;tree.children.forEach(m=>m.castShadow=true);this.scene.add(tree);}
    for(let i=0;i<18;i++){const a=i*.43,x=-20+Math.cos(a)*24,z=5+Math.sin(a)*18,b=new THREE.Mesh(new THREE.BoxGeometry(4+(i%3),3+(i%4),4),new THREE.MeshStandardMaterial({color:'#eadcbc',roughness:.9}));b.position.set(x,b.geometry.parameters.height/2,z);b.castShadow=true;this.scene.add(b);const roof=new THREE.Mesh(new THREE.ConeGeometry(3.8,1.4,4),new THREE.MeshStandardMaterial({color:'#a1452d'}));roof.position.set(x,b.geometry.parameters.height+.6,z);roof.rotation.y=Math.PI/4;roof.castShadow=true;this.scene.add(roof);}
  }
  private makeClouds(){const mat=new THREE.MeshBasicMaterial({color:'#f4e8ce',fog:false});for(let i=0;i<13;i++){const g=new THREE.Group();for(let j=0;j<7;j++){const s=8+(j*7%10),m=new THREE.Mesh(new THREE.SphereGeometry(s,10,7),mat);m.scale.y=.58;m.position.set(j*8,Math.sin(j)*4,0);g.add(m);}g.position.set(-240+(i%5)*110,70+(i%3)*25,-260+Math.floor(i/5)*190);this.scene.add(g);}}
  private makeCar(colour:string,number:number){const g=new THREE.Group(),bodyMat=new THREE.MeshPhysicalMaterial({color:colour,metalness:.48,roughness:.22,clearcoat:1,clearcoatRoughness:.12}),carbon=new THREE.MeshStandardMaterial({color:'#080a0b',roughness:.3,metalness:.65}),rubber=new THREE.MeshStandardMaterial({color:'#050505',roughness:.82});const add=(geo:THREE.BufferGeometry,mat:THREE.Material,x:number,y:number,z:number)=>{const m=new THREE.Mesh(geo,mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;g.add(m);return m};
    add(new THREE.CapsuleGeometry(.72,3.7,8,16),bodyMat,0,.42,0);add(new THREE.BoxGeometry(1.85,.58,2.25),bodyMat,0,.48,-.45);add(new THREE.ConeGeometry(.62,3.3,6),bodyMat,0,.33,2.5).rotation.x=Math.PI/2;add(new THREE.BoxGeometry(4.7,.12,.72),carbon,0,.22,3.75);add(new THREE.BoxGeometry(3.2,.16,.7),carbon,0,1.15,-2.55);add(new THREE.BoxGeometry(.16,1.18,.18),carbon,-1.35,.62,-2.55);add(new THREE.BoxGeometry(.16,1.18,.18),carbon,1.35,.62,-2.55);add(new THREE.TorusGeometry(.62,.09,8,20,Math.PI*1.45),carbon,0,1.05,.25).rotation.x=Math.PI/2;
    const wheels:THREE.Mesh[]=[];for(const x of [-1.36,1.36])for(const z of [-1.7,2.0]){const w=add(new THREE.CylinderGeometry(.5,.5,.36,20),rubber,x,.43,z);w.rotation.z=Math.PI/2;wheels.push(w);const hub=add(new THREE.CylinderGeometry(.22,.22,.39,12),new THREE.MeshStandardMaterial({color:'#d7a647',metalness:.9,roughness:.2}),x,.43,z);hub.rotation.z=Math.PI/2;}const plate=add(new THREE.BoxGeometry(.78,.02,.48),new THREE.MeshBasicMaterial({color:'#f4e8ce'}),0,1.25,-2.55);plate.rotation.x=-.08;plate.userData.number=number;g.userData.wheels=wheels;g.scale.setScalar(.72);return g;}
  dispose(){cancelAnimationFrame(this.raf);removeEventListener('resize',this.resize);this.renderer.dispose();this.el.removeChild(this.renderer.domElement);}
}
