import type { CSSProperties } from 'react';
import type { TrackDefinition } from '@agp/sim-core';
import { trackPoint } from '@agp/sim-core';
import { ENTRANTS,TEAMS } from './championship';

export type WeekendStage='PRACTICE'|'QUALIFYING'|'GRAND_PRIX';

export function WeekendPanel({track,completed,qualifyingOrder,onRun,onBack}:{track:TrackDefinition;completed:WeekendStage[];qualifyingOrder:string[];onRun:(stage:WeekendStage)=>void;onBack:()=>void}){
  const practiceDone=completed.includes('PRACTICE'),qualifyingDone=completed.includes('QUALIFYING'),raceDone=completed.includes('GRAND_PRIX');
  return <section className="panel-screen cwc-weekend"><header className="panel-head"><button className="mini-brand" onClick={onBack}><b>AI</b><span>GRAND PRIX</span></button><div><small>ROUND {String(track.round).padStart(2,'0')} · {track.country.toUpperCase()}</small><h2>RACE WEEKEND</h2></div><button className="close" onClick={onBack}>BACK</button></header><div className="cwc-weekend-body"><div className="cwc-weekend-copy"><small>CONNECTOME WORLD CHAMPIONSHIP · {track.dates}</small><h3>{track.grandPrix.toUpperCase()}</h3><WeekendTrack trackId={track.id}/><p>Practice lets all 22 phenotypes settle into {track.circuitName}. Qualifying ranks them by best lap. That order becomes the starting grid for the points-paying Grand Prix.</p>{track.sprint&&<span className="cwc-sprint-badge">2027 SPRINT VENUE</span>}<div className="cwc-weekend-teams">{TEAMS.map(t=><i key={t.id} title={t.name} style={{background:t.colour}}/>)}</div></div><div className="cwc-session-stack"><Session n="01" title="PRACTICE" state={practiceDone?'COMPLETE':'READY'} description="Three laps. Open running. No championship points." onClick={()=>onRun('PRACTICE')}/><Session n="02" title="QUALIFYING" state={qualifyingDone?'COMPLETE':practiceDone?'READY':'LOCKED'} description="Three laps. Best lap sets the 22-car starting order." disabled={!practiceDone&&!qualifyingDone} onClick={()=>onRun('QUALIFYING')}/><Session n="03" title="GRAND PRIX" state={raceDone?'COMPLETE':qualifyingDone?'READY':'LOCKED'} description="Points-paying race. Constructor tuning and pit strategy active." disabled={!qualifyingDone&&!raceDone} onClick={()=>onRun('GRAND_PRIX')}/></div>{qualifyingOrder.length>0&&<section className="cwc-grid-preview"><header><small>QUALIFYING CLASSIFICATION</small><strong>PROVISIONAL STARTING GRID</strong></header><div>{qualifyingOrder.map((id,i)=>{const d=ENTRANTS.find(x=>x.id===id);if(!d)return null;return <span key={id} style={{'--driver':d.colour} as CSSProperties}><b>{i+1}</b><i/><strong>{d.short}</strong><small>#{d.number}</small></span>})}</div></section>}</div></section>
}

function WeekendTrack({trackId}:{trackId:string}){const pts=Array.from({length:110},(_,i)=>trackPoint(i/110,trackId)),minX=Math.min(...pts.map(p=>p.x)),maxX=Math.max(...pts.map(p=>p.x)),minZ=Math.min(...pts.map(p=>p.z)),maxZ=Math.max(...pts.map(p=>p.z)),span=Math.max(maxX-minX,maxZ-minZ)||1,path=pts.map((p,i)=>`${i?'L':'M'} ${8+(p.x-minX)/span*84} ${8+(p.z-minZ)/span*84}`).join(' ')+' Z';return <svg className="cwc-weekend-track" viewBox="0 0 100 100"><path d={path}/></svg>}
function Session({n,title,state,description,onClick,disabled=false}:{n:string;title:string;state:string;description:string;onClick:()=>void;disabled?:boolean}){return <button className={`cwc-session ${state.toLowerCase()}`} disabled={disabled} onClick={onClick}><small>{n} · {state}</small><strong>{title}</strong><span>{description}</span><b>{state==='COMPLETE'?'✓':'→'}</b></button>}
