import type { CSSProperties } from 'react';
import { ENTRANTS,TEAMS } from './championship';

export type WeekendStage='PRACTICE'|'QUALIFYING'|'GRAND_PRIX';

export function WeekendPanel({completed,qualifyingOrder,onRun,onBack}:{completed:WeekendStage[];qualifyingOrder:string[];onRun:(stage:WeekendStage)=>void;onBack:()=>void}){
  const practiceDone=completed.includes('PRACTICE'),qualifyingDone=completed.includes('QUALIFYING'),raceDone=completed.includes('GRAND_PRIX');
  return <section className="panel-screen cwc-weekend"><header className="panel-head"><button className="mini-brand" onClick={onBack}><b>AI</b><span>GRAND PRIX</span></button><div><small>ROUND 01 · AZURE COAST</small><h2>RACE WEEKEND</h2></div><button className="close" onClick={onBack}>BACK</button></header><div className="cwc-weekend-body"><div className="cwc-weekend-copy"><small>CONNECTOME WORLD CHAMPIONSHIP</small><h3>THREE SESSIONS.<br/>ONE GRID.</h3><p>Practice lets all 22 phenotypes settle into the circuit. Qualifying ranks them by best lap. That order becomes the starting grid for the points-paying Grand Prix.</p><div className="cwc-weekend-teams">{TEAMS.map(t=><i key={t.id} title={t.name} style={{background:t.colour}}/>)}</div></div><div className="cwc-session-stack"><Session n="01" title="PRACTICE" state={practiceDone?'COMPLETE':'READY'} description="Three laps. Open running. No championship points." onClick={()=>onRun('PRACTICE')}/><Session n="02" title="QUALIFYING" state={qualifyingDone?'COMPLETE':practiceDone?'READY':'LOCKED'} description="Three laps. Best lap sets the 22-car starting order." disabled={!practiceDone&&!qualifyingDone} onClick={()=>onRun('QUALIFYING')}/><Session n="03" title="GRAND PRIX" state={raceDone?'COMPLETE':qualifyingDone?'READY':'LOCKED'} description="Points-paying race. Constructor tuning and pit strategy active." disabled={!qualifyingDone&&!raceDone} onClick={()=>onRun('GRAND_PRIX')}/></div>{qualifyingOrder.length>0&&<section className="cwc-grid-preview"><header><small>QUALIFYING CLASSIFICATION</small><strong>PROVISIONAL STARTING GRID</strong></header><div>{qualifyingOrder.map((id,i)=>{const d=ENTRANTS.find(x=>x.id===id);if(!d)return null;return <span key={id} style={{'--driver':d.colour} as CSSProperties}><b>{i+1}</b><i/><strong>{d.short}</strong><small>#{d.number}</small></span>})}</div></section>}</div></section>
}

function Session({n,title,state,description,onClick,disabled=false}:{n:string;title:string;state:string;description:string;onClick:()=>void;disabled?:boolean}){return <button className={`cwc-session ${state.toLowerCase()}`} disabled={disabled} onClick={onClick}><small>{n} · {state}</small><strong>{title}</strong><span>{description}</span><b>{state==='COMPLETE'?'✓':'→'}</b></button>}
