import { mkdir,writeFile } from 'node:fs/promises';import { dirname,resolve } from 'node:path';import { fileURLToPath } from 'node:url';
import { RaceSimulation,createCar,FIXED_DT } from '@agp/sim-core';import { DeterministicDriver,decisionToControl,observe } from '@agp/driver-sdk';import { VERSION,type Control } from '@agp/shared';
const here=dirname(fileURLToPath(import.meta.url)),root=resolve(here,'../../..');
const entries=[['gpt','GPT',10,'#101312',.8],['claude','CLAUDE',32,'#D97757',.35],['gemini','GEMINI',88,'#4285F4',.55],['grok','GROK',24,'#050708',.9],['qwen','QWEN',72,'#615CED',.15],['deepseek','DEEPSEEK',1,'#4D6BFE',-.1],['mistral','MISTRAL',7,'#F97316',.65],['llama','LLAMA',70,'#0668E1',-.35]] as const;
interface ReplayFrame{t:number;cars:Array<{id:string;x:number;z:number;yaw:number;speed:number;lap:number;position:number;status:string}>}
const sim=new RaceSimulation(entries.map((e,i)=>createCar(e[0],e[1],e[2],e[3],i)),3,4127);const drivers=new Map<string,DeterministicDriver>(entries.map(e=>[e[0],new DeterministicDriver(e[0],e[1],e[4])]));const controls=new Map<string,Control>(),frames:ReplayFrame[]=[],events:unknown[]=[];
const capture=()=>({t:+sim.state.time.toFixed(3),cars:sim.state.cars.map(c=>({id:c.id,x:+c.x.toFixed(3),z:+c.z.toFixed(3),yaw:+c.yaw.toFixed(5),speed:+c.speed.toFixed(2),lap:c.lap,position:c.position,status:c.status}))});
while(sim.state.flag!=='CHEQUERED'&&sim.state.time<360){if(sim.state.tick%30===0){for(const car of sim.state.cars){const d=drivers.get(car.id)!;controls.set(car.id,decisionToControl(await d.decide(observe(sim.state,car))));}}sim.step(controls,FIXED_DT);if(sim.state.tick%48===0)frames.push(capture());}if(frames.at(-1)?.t!==+sim.state.time.toFixed(3))frames.push(capture());
for(const c of sim.state.cars)events.push({type:'CLASSIFICATION',car:c.id,position:c.position,status:c.status,bestLap:c.bestLap});
const replay={format:'AGPR/1',createdAt:new Date().toISOString(),classification:'NON-BENCHMARK',reason:'Deterministic offline reference drivers',versions:VERSION,seed:sim.state.seed,laps:sim.laps,frames,events};const output=resolve(root,'data/races/latest.agpr.json');await mkdir(dirname(output),{recursive:true});await writeFile(output,JSON.stringify(replay));console.log(`Race complete: ${sim.state.time.toFixed(2)}s, ${frames.length} frames`);console.log(`Replay: ${output}`);
