import { z } from 'zod';
import type { CarState, Control, RaceState } from '@agp/shared';
import { nearestTrack, trackPoint, trackTangent, TRACK_LENGTH, clamp } from '@agp/sim-core';

export const DecisionSchema=z.object({horizonSeconds:z.number().min(.25).max(6),controls:z.array(z.object({t:z.number().min(0).max(6),steering:z.number(),throttle:z.number(),brake:z.number()})).min(1).max(16),energyDeploy:z.number().default(0),pitRequest:z.boolean().default(false),tyreRequest:z.enum(['SOFT','MEDIUM','HARD','INTERMEDIATE','WET']).nullable().default(null),strategyIntent:z.string().max(180).default(''),radio:z.string().max(180).default(''),memoryUpdate:z.string().max(8000).default('')});
export type DriverDecision=z.infer<typeof DecisionSchema>;
export interface DriverObservation{car:CarState;race:{time:number;lap:number;position:number;flag:string};track:Array<{distance:number;headingDelta:number;leftBoundary:number;rightBoundary:number}>;nearby:Array<{id:string;distance:number;relativeSpeed:number}>;}
export interface DriverAdapter{id:string;provider:string;displayName:string;initialize():Promise<void>;decide(observation:DriverObservation,memory:string):Promise<DriverDecision>;shutdown():Promise<void>;}
export function observe(state:RaceState,car:CarState):DriverObservation{
  const samples=[0,10,20,40,60,80,120,160,220,300].map(distance=>{const advance=distance/TRACK_LENGTH;const tan=trackTangent((car.progress+advance)%1);let d=tan.yaw-car.yaw;while(d>Math.PI)d-=Math.PI*2;while(d<-Math.PI)d+=Math.PI*2;return{distance,headingDelta:d,leftBoundary:6,rightBoundary:6};});
  return {car,race:{time:state.time,lap:car.lap,position:car.position,flag:state.flag},track:samples,nearby:state.cars.filter(c=>c.id!==car.id).map(c=>({id:c.id,distance:Math.hypot(c.x-car.x,c.z-car.z),relativeSpeed:c.speed-car.speed})).filter(c=>c.distance<80)};
}
export class DeterministicDriver implements DriverAdapter{
  provider='OFFLINE'; displayName:string;private lineBias:number;private braking:number;private attack:number;
  constructor(public id:string,name:string,private temperament=0){this.displayName=name;const hash=[...id].reduce((n,c)=>((n*31+c.charCodeAt(0))>>>0),17);this.lineBias=((hash%101)/100-.5)*2.5;this.braking=.97+((hash>>3)%9)/200;this.attack=.54+((hash>>7)%28)/100;}
  async initialize(){} async shutdown(){}
  async decide(o:DriverObservation):Promise<DriverDecision>{const c=o.car,near=nearestTrack(c.x,c.z),look=clamp(.02+c.speed/TRACK_LENGTH*.5,.02,.082),targetT=(near.t+look)%1,target=trackPoint(targetT),tan=trackTangent(targetT),traffic=o.nearby.filter(n=>n.distance<11).length,attackSide=((Math.floor(o.race.time/8)+this.id.length)%2?1:-1),offset=traffic&&o.race.time>6?attackSide*(1.7+this.attack):this.lineBias;target.x+=tan.z*offset;target.z-=tan.x*offset;const desired=Math.atan2(target.x-c.x,target.z-c.z);let error=desired-c.yaw;while(error>Math.PI)error-=Math.PI*2;while(error<-Math.PI)error+=Math.PI*2;const corner=Math.max(Math.abs(o.track[4].headingDelta),Math.abs(o.track[6].headingDelta),Math.abs(o.track[7].headingDelta)),targetSpeed=clamp((89-corner*42+this.temperament*1.4)*this.braking,26,96),brake=clamp((c.speed-targetSpeed)/(14-this.attack),0,1),throttle=clamp((targetSpeed-c.speed)/14+.5,0,1)*(1-brake),deployWindow=(o.race.time*.11+this.attack)%1,deploy=c.battery>.15&&throttle>.82&&(traffic>0||deployWindow>.58)?clamp(.55+this.attack*.45,0,1):0;return {horizonSeconds:.25,controls:[{t:0,steering:clamp(error*(2.48+this.attack*.2),-1,1),throttle,brake}],energyDeploy:deploy,pitRequest:false,tyreRequest:null,strategyIntent:traffic?'ATTACK':'BUILD GAP',radio:traffic?'ATTACK MODE':'',memoryUpdate:''};}
}
export function decisionToControl(d:DriverDecision):Control{const p=d.controls[0];return{steering:clamp(p.steering,-1,1),throttle:clamp(p.throttle,0,1),brake:clamp(p.brake,0,1),energyDeploy:clamp(d.energyDeploy,0,1)};}
